### ISSUE TITLE
[yggtorrent] Error: Error solving the challenge. Message: unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by arnaudalexis** [FlareSolverr/FlareSolverr#1029]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.12
- Last working FlareSolverr version: 3.3.8
- Operating system: Linux-5.15.0-86-generic-x86_64-with-glibc2.31
- Are you using Docker: not sure as i am using a saas provider
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- URL to test this issue: https://www3.yggtorrent.qa/engine/search?category=2145&do=search&order=desc&sort=publish_date
```

### Description

Hi, after trying different releases (3.3.8 to 3.3.12), there is an issue when trying to access Yggtorrent tracker. 
I've already had a look at different topics to solve this but without success.
I'm not sure if the app is deployed via Docker as im using a Saas platform to install it on a remote server.

Here are the params sent : 
`{
    "maxTimeout": 180000,
    "cmd": "request.get",
    "url": "https://www3.yggtorrent.qa/engine/search?category=2145&do=search&order=desc&sort=publish_date",
    "proxy": {}
}`

Env variables : 
`LANG=en_US.UTF-8`

I'm successfully reaching iDope, TorrentQQ and Torrent[Core].

Also i've tried to replicate the issue on Windows on another network but i can't trigger the challenge.

Could my issue be related to an ip range ban on ygg side ? 

### Logged Error Messages

```text
Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\\nfrom unknown error: cannot determine loading status\\nfrom tab crashed\\n  (Session info: chrome=120.0.6099.129)\\nStacktrace:\\n#0 0x559a05ad6f83 <unknown>\\n#1 0x559a0578fb2b <unknown>\\n#2 0x559a0577716d <unknown>\\n#3 0x559a05776882 <unknown>\\n#4 0x559a05775586 <unknown>\\n#5 0x559a0577544a <unknown>\\n#6 0x559a057737e1 <unknown>\\n#7 0x559a0577418a <unknown>\\n#8 0x559a0578507c <unknown>\\n#9 0x559a0579d7c1 <unknown>\\n#10 0x559a057a36bb <unknown>\\n#11 0x559a0577492d <unknown>\\n#12 0x559a0579d459 <unknown>\\n#13 0x559a05827f1a <unknown>\\n#14 0x559a05808e53 <unknown>\\n#15 0x559a057d0dd4 <unknown>\\n#16 0x559a057d21de <unknown>\\n#17 0x559a05a9b531 <unknown>\\n#18 0x559a05a9f455 <unknown>\\n#19 0x559a05a87f55 <unknown>\\n#20 0x559a05aa00ef <unknown>\\n#21 0x559a05a6b99f <unknown>\\n#22 0x559a05ac4008 <unknown>\\n#23 0x559a05ac41d7 <unknown>\\n#24 0x559a05ad6124 <unknown>\\n#25 0x7fb78d21fea7 start_thread\\n
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/13242679/422c03d1-900f-4391-b974-3134afbab51e)

**Comment by ilike2burnthing** [comment]
There have been a few issues now of Chrome crashing for seemingly no reason. It's then stranger that only one site is causing crashes for you and not others.

Are you using a proxy or VPN? If yes, drop it. If no, try it and test your IP range theory.

**Comment by arnaudalexis** [comment]
Hi, not using a vpn nor a proxy. I've had one successfull call yesterday (challenge found and resolved) but that only happend once.
I find it strange that one call worked if the ip is banned but i will have a look.
I also confirm that it is working fine with other indexers !

**Comment by ilike2burnthing** [comment]
Unlikely to resolve your issue, but [v3.3.13](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.13) is now out, please try it.

**Comment by arnaudalexis** [comment]
Hi !
I've just updated to the latest release but unfortunately issue persists.
Had a talk with somebody having the exact same crash / error with ygg.
I don't know if i can provide more logs than what i did in my first post but i will use other indexers for now !

Have a nice day

**Comment by arnaudalexis** [comment]
Quick update, requests are still crashing. I can access the website with a browser on the same env.
I can't replicate the issue on other envs because i don't get the cloudflare challenge there.
It takes from 10 to 25 s before crashing.

**Comment by deviltuner** [comment]
same thing

**Comment by sgelineau17** [comment]
Hello,

Any feedback ?
I have the same problem on my side. 

Thanks

**Comment by ilike2burnthing** [comment]
Any updates will be posted here. I can't recreate the issue, so this is reliant on a contribution, a definite cause being identified, or an update to our dependencies which solves it out of the blue.

**Comment by arnaudalexis** [comment]
Hi, i can provide more details if needed, would enabling LOG_LEVEL debug be useful ?

**Comment by ilike2burnthing** [comment]
Feel free to provide debug logs, however similar issues tend to just show a few retries and then it crashes with no discernible cause.

**Comment by Al4ndil** [comment]
Hi, I think I have a problem with yggtorrent and flaresolverr. It seems that flaresolverr does not resolve Cloudflare. Prowlarr means it is blocked by Cloudflare with YggCookie. I can provide a debug log if needed.

**Comment by Siouldlh** [comment]
Yes I have the same problem flarre solver no longer works for ygg

**Comment by arnaudalexis** [comment]
Hi, quick follow-up, issue still occurs with 3.3.15.
Can't give you much more details, same error.

**Comment by ilike2burnthing** [comment]
Please test with [v3.3.16](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.16).

**Comment by Axel4602** [comment]
Same problem here, unfortunaly with v3.3.16

**Comment by HellxGodLike** [comment]
anyone else facing same issue? error in solving

**Comment by MastaG** [comment]
Based on the Dockerfile it seems Flaresolverr is using the Chromium package from the debian bullseye repository:
```apt-get install -y --no-install-recommends chromium chromium-common chromium-driver```
Did anybody try the official chrome browser from Google? (e.g. modify the Dockerfile to just install the official .deb package instead)

This wouldn't work for arm but perhaps it's worth a shot.

**Comment by Axel4602** [comment]
GG GUYS !!! updated Flaresolverr to .17 and it's working <3 love

**Comment by Axel4602** [comment]
GG GUYS !!! Updated flaresolverr to .17 and Ygg indexer finally works (automatic, RSS, INTERACTIV). Thanks a lot <3 love

**Comment by MastaG** [comment]
.17 didnt fix things for me 
```
2024-04-10 20:56:29 INFO     FlareSolverr 3.3.17
2024-04-10 20:56:29 INFO     Testing web browser installation...
2024-04-10 20:56:29 INFO     Platform: Linux-6.8.4-300.fc40.x86_64-x86_64-with-glibc2.31
2024-04-10 20:56:29 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-04-10 20:56:29 INFO     Chrome / Chromium major version: 120
2024-04-10 20:56:29 INFO     Launching web browser...
version_main cannot be converted to an integer
2024-04-10 20:56:30 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-04-10 20:56:30 INFO     Test successful!
2024-04-10 20:56:30 INFO     Serving on http://0.0.0.0:8191
2024-04-10 20:56:50 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://bitturk.net/?p=torrents&pid=32&search_type=name&searchin=title&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-10 20:56:51 INFO     Challenge detected. Title found: Just a moment...
2024-04-10 20:57:51 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-04-10 20:57:51 INFO     Response in 60.795 s
2024-04-10 20:57:51 INFO     192.168.1.1 POST http://192.168.1.1:8191/v1 500 Internal Server Error
```

**Comment by u2pitchjami** [comment]
hi,
it's seems good for me since i desactived ipv6 on my unraid server

**Comment by TEALC82** [comment]
No longer works since changing domain, despite deactivating IPv6 in docker compose
`sysctls:
      - net.ipv6.conf.all.disable_ipv6=1`

**Comment by Axel4602** [comment]
> No longer works since changing domain, despite deactivating IPv6 in docker compose `sysctls: - net.ipv6.conf.all.disable_ipv6=1`

Same here ...

**Comment by Reivilo85k** [comment]
Same here :
```
2024/05/01 14:57:07 | stdout | 2024-05-01 11:57:07 INFO     172.17.0.1 POST http://192.168.0.25:8191/v1 500 Internal Server Error
-- | -- | --
2024/05/01 14:57:07 | stdout | 2024-05-01 11:57:07 INFO     Response in 56.388 s
2024/05/01 14:57:07 | stdout | 2024-05-01 11:57:07 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024/05/01 14:56:25 | stdout | 2024-05-01 11:56:25 INFO     172.17.0.1 GET http://192.168.0.25:8191/ 200 OK
2024/05/01 14:56:16 | stdout | 2024-05-01 11:56:16 INFO     Challenge detected. Title found: Just a moment...
2024/05/01 14:56:10 | stdout | version_main cannot be converted to an integer
2024/05/01 14:56:10 | stdout | 2024-05-01 11:56:10 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2024/05/01 14:55:45 | stdout | 2024-05-01 11:55:45 INFO     Serving on http://0.0.0.0:8191
2024/05/01 14:55:45 | stdout | 2024-05-01 11:55:45 INFO     Test successful!
2024/05/01 14:55:45 | stdout | 2024-05-01 11:55:45 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024/05/01 14:55:42 | stdout | version_main cannot be converted to an integer
2024/05/01 14:55:42 | stdout | 2024-05-01 11:55:42 INFO     Launching web browser...
2024/05/01 14:55:42 | stdout | 2024-05-01 11:55:42 INFO     Chrome / Chromium major version: 120
2024/05/01 14:55:40 | stdout | 2024-05-01 11:55:40 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/05/01 14:55:40 | stdout | 2024-05-01 11:55:40 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.31
2024/05/01 14:55:40 | stdout | 2024-05-01 11:55:40 INFO     Testing web browser installation...
2024/05/01 14:55:40 | stdout | 2024-05-01 11:55:40 INFO     FlareSolverr 3.3.17
```

**Comment by Rucan69** [comment]
> No longer works since changing domain, despite deactivating IPv6 in docker compose `sysctls: - net.ipv6.conf.all.disable_ipv6=1`

Same here, timeout since domain change to .cool

**Comment by sodanexus** [comment]
Ever since switching to the .cool domain, Flaresolverr has been unable to successfully complete the challenge. Whether it's an English language environment or IPv6 disabled, it just doesn't work. What should I do? Should I wait for an update? Or has someone found a solution? I've tried pretty much everything I could :/

**Comment by ilike2burnthing** [comment]
Are you getting the error `session deleted because of page crash`? If not, you're probably looking for #1036

**Comment by sodanexus** [comment]
> Are you getting the error `session deleted because of page crash`? If not, you're probably looking for #1036

Thank you for your response, I've tried quite a few things on this ticket, changing the user agent, using the 21hsmw fork. I don't know if it's useful information, but I'm used to yggtorrent and flaresolverr, many have talked about it on the yggtorrent forum for a long time! You're kind of a savior lol. From what I can read, it seems that there has been an additional security added to yggtorrent. I hope it's not true. Yggtorrent is probably the largest tracker in France, that's probably why you have to moderate more than usual right now...

Anyway, thank you for your work. I'll wait on my side and be patient while monitoring the ygg forum and your GitHub! Cheers!

**Comment by sodanexus** [comment]
Problem solved with the fork of Juanfrillaaa on Linux without VPN or proxy 

https://github.com/FlareSolverr/FlareSolverr/pull/1163#issuecomment-2093855103

**Comment by skjnldsv** [comment]
> Problem solved with the fork of Juanfrillaaa on Linux without VPN or proxy (for yggtorrent)
> 
> https://github.com/FlareSolverr/FlareSolverr/pull/1163#issuecomment-2093855103
> 

Doesn't work for me.
Are you on windows?

**Comment by nodiaque** [comment]
I guess it's not solve on the official docker? Cause I'm still getting the error with  3.3.21 docker

**Comment by ilike2burnthing** [comment]
See pinned issues and latest PRs.

**Comment by zobi** [comment]
same issue for me

**Comment by thiagocrepaldi** [comment]
try increasing your ram memory
