### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported 

### ISSUE THREAD

**Issue by Seidel76** [FlareSolverr/FlareSolverr#140]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v1.2.6
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes]
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

2021-05-30T17:40:00+00:00 INFO REQ-1 Incoming request: POST /v1
2021-05-30T17:40:00+00:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-05-30T17:40:00+00:00 DEBUG REQ-1 Launching browser...
2021-05-30T17:40:00+00:00 DEBUG REQ-1 Using custom UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
2021-05-30T17:40:00+00:00 DEBUG REQ-1 Adding custom headers: {}
2021-05-30T17:40:00+00:00 DEBUG REQ-1 Navigating to... https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2021-05-30T17:40:00+00:00 DEBUG REQ-1 Overrides: {"headers":{"upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}}
2021-05-30T17:40:01+00:00 INFO REQ-1 Cloudflare detected
2021-05-30T17:40:01+00:00 DEBUG REQ-1 No '#trk_jschal_js' challenge element detected.
2021-05-30T17:40:01+00:00 DEBUG REQ-1 No '.ray_id' challenge element detected.
2021-05-30T17:40:01+00:00 DEBUG REQ-1 No '.attack-box' challenge element detected.
2021-05-30T17:40:01+00:00 DEBUG REQ-1 Javascript challenge element '#cf-please-wait' detected.
2021-05-30T17:40:01+00:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
2021-05-30T17:40:12+00:00 DEBUG REQ-1 Validating HTML code...
2021-05-30T17:40:12+00:00 DEBUG REQ-1 Javascript challenge selectors found: 1, total selectors: 4
2021-05-30T17:40:12+00:00 INFO REQ-1 Captcha challenge detected.
2021-05-30T17:40:12+00:00 INFO REQ-1 Using 'hcaptcha-solver' to solve the captcha.
2021-05-30T17:40:12+00:00 INFO REQ-1 Waiting to receive captcha token to bypass challenge...
2021-05-30T17:40:12+00:00 INFO REQ-1 Response in 11.466 s
2021-05-30T17:40:12+00:00 INFO REQ-1 Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Oyo95** [comment]
Hi,

I have de same issue...

> flaresolverr@1.2.6 start
> node ./dist/index.js
2021-05-30T18:50:14+00:00 INFO FlareSolverr v1.2.6
2021-05-30T18:50:14+00:00 DEBUG Debug log enabled
2021-05-30T18:50:14+00:00 INFO Using 'hcaptcha-solver' to solve the captcha.
2021-05-30T18:50:14+00:00 DEBUG Testing Chrome installation...
2021-05-30T18:50:14+00:00 DEBUG Launching browser...
2021-05-30T18:50:17+00:00 DEBUG Test successful
2021-05-30T18:50:17+00:00 INFO Listening on http://0.0.0.0:8191
2021-05-30T18:50:20+00:00 INFO REQ-1 Incoming request: POST /v1
2021-05-30T18:50:20+00:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-05-30T18:50:20+00:00 DEBUG REQ-1 Launching browser...
2021-05-30T18:50:21+00:00 DEBUG REQ-1 Using custom UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
2021-05-30T18:50:21+00:00 DEBUG REQ-1 Adding custom headers: {}
2021-05-30T18:50:21+00:00 DEBUG REQ-1 Navigating to... https://www4.yggtorrent.li/
2021-05-30T18:50:21+00:00 DEBUG REQ-1 Overrides: {"headers":{"upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}}
2021-05-30T18:50:22+00:00 INFO REQ-1 Cloudflare detected
2021-05-30T18:50:22+00:00 DEBUG REQ-1 No '#trk_jschal_js' challenge element detected.
2021-05-30T18:50:22+00:00 DEBUG REQ-1 No '.ray_id' challenge element detected.
2021-05-30T18:50:22+00:00 DEBUG REQ-1 No '.attack-box' challenge element detected.
2021-05-30T18:50:22+00:00 DEBUG REQ-1 Javascript challenge element '#cf-please-wait' detected.
2021-05-30T18:50:22+00:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
2021-05-30T18:50:33+00:00 DEBUG REQ-1 Validating HTML code...
2021-05-30T18:50:33+00:00 DEBUG REQ-1 Javascript challenge selectors found: 1, total selectors: 4
2021-05-30T18:50:33+00:00 INFO REQ-1 Captcha challenge detected.
2021-05-30T18:50:33+00:00 INFO REQ-1 Using 'hcaptcha-solver' to solve the captcha.
2021-05-30T18:50:33+00:00 INFO REQ-1 Waiting to receive captcha token to bypass challenge...
2021-05-30T18:50:33+00:00 INFO REQ-1 Response in 12.585 s
2021-05-30T18:50:33+00:00 INFO REQ-1 Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.


FlareSolverr version: v1.2.6
Last working FlareSolverr version: V1.2.5
Operating system: Docker with portainer (On synology DS920+)
Are you using Docker: [yes]
Are you using a proxy or VPN? [no]
Are you using Captcha Solver: [no]
URL to test this issue: https://www4.yggtorrent.li/

**Comment by charliik** [comment]
Same issue

**Comment by Mrpink200** [comment]
same

**Comment by nini57** [comment]
same

**Comment by almottier** [comment]
I temporarily fixed it by changing my IP.

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 solves the issue for most users including myself.
For those with the captcha issue, there is no easy fix. FlareSolverr is not able to resolve the image captcha challenge. You have to keep trying. Some users said that they Cloudflare removes the captcha after you resolves it manually in the web browser. Others fix it changing the public IP. As I said, there is no easy solution. I hope they will remove the captcha eventually.

**Comment by hbouhadji** [comment]
maybe implementation of some services like 2captcha ?

**Comment by ngosang** [comment]
Released FlareSolverr 1.2.7
Please, try again.

**Comment by trygun03** [comment]
Not work :( Thank you very much.

**Comment by ngosang** [comment]
Last minute fix FlareSolverr 1.2.8

**Comment by yonix06** [comment]
Hello,
I have tried every answer on this github regarding this issue,
I'm currently in 1.2.8, Docker image from ghcr.io

Still not working, 

-Harvester : "Cloudflare TypeError: Cannot read property 'statusCode' of undefined" 
with env parameter HARVESTER_ENDPOINT=https://127.0.0.1:5000/token

-hcaptcha-solver: "Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge."

Just letting you know, 
Thanks a lot for your hard work.

**Comment by charly925** [comment]
> -Harvester : "Cloudflare TypeError: Cannot read property 'statusCode' of undefined"
> with env parameter HARVESTER_ENDPOINT=https://127.0.0.1:5000/token

Hi,
I had the same issue here.
I changed my public IP (with a VPN or a different VPN, or by desactivating your VPN for example), opened a regular on the computer where flaresolverr is running, opend a cloudfare webpage, solved a challenge... And then flaresolverr started working.

Good luck

**Comment by Samhot** [comment]
Hi,
I updated to 1.2.8 and it's still not working... I can't change my public IP because my entire stack is on a dedicated server

**Comment by charly925** [comment]
It's a bit random.
Just wait until it works (can take few hours)
Good luck

**Comment by yonix06** [comment]
> opened a regular on the computer where flaresolverr is running, opend a cloudfare webpage, solved a challenge... And then flaresolverr started working.

That's an interesting lead.

**Comment by Ptikrazy** [comment]
> 
> 
> > opened a regular on the computer where flaresolverr is running, opend a cloudfare webpage, solved a challenge... And then flaresolverr started working.
> 
> That's an interesting lead.

Indeed, but sadly for headless setups such as mine, I can't figure out how to do it :(

**Comment by charly925** [comment]
Did you try to do it from a regular computer that would have the same public IP as your headless server ?

**Comment by Mrpink200** [comment]
i did. my flaresolder is on a docker on my NAS, and my laptop is on the same network
solving the challenge does not fix the problem :(

**Comment by Razor648** [comment]
> i did. my flaresolder is on a docker on my NAS, and my laptop is on the same network
> solving the challenge does not fix the problem :(

same for me.

**Comment by Ptikrazy** [comment]
> 
> 
> Did you try to do it from a regular computer that would have the same public IP as your headless server ?

I deed, and as the previous answers, sadly it did not work. Just have to wait for them to disable the captcha !

**Comment by charly925** [comment]
It can also be related to your IP being categorized by cloudfare or something.
Do you have any way to change your public IP (VPN for example) ?

**Comment by Ptikrazy** [comment]
> 
> 
> It can also be related to your IP being categorized by cloudfare or something.
> Do you have any way to change your public IP (VPN for example) ?

Not really, my FAI changes it every few months so I guess I'll wait

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I having the same issue as you (for yggtorrent on my side). I understand it's complicated as captcha can't be easily solved by FlareSolverr. But I may have found an temporary fix, if you need to access yggtorrent right now and your IP has been set to "captcha required" by Cloudflare:

First, connect to ygg with your PC, solving the captcha if needed.
Then, setup YGGcookie on Jackett (use its instructions) using the cookie header from your PC.
Then, test that YGGcookie is working.
Then, test that YGGtorrent is working.
It should now work again !

I think it works because it does the following: You completed the captcha on your PC, so the cookie header on your PC now includes the information that the captcha is solved (so Cloudflare lets you in). Then, you passed this cookie to YGGcookie, so it succeeds to connect too. Then, this cookie is memorized by FlareSolverr, that will use it for all connections to yggtorrent (so both YGGcookie and YGGtorrent indexers in Jackett). So now, if you try to connect to YGGtorrent, it will work too as it is using the cookie from YGGcookie.

Of course, it will still fail after some time of if too much requests, because Cloudflare will say that your cookie header is no longer valid. You need to wait, or to do this again to pass a new cookie header to YGGcookie/YGGtorrent.

If that situation continues for too long, there could be a solution. Maybe it's possible to make a software that allows to quickly solve the captcha, by sending it to an app for PC or mobile that looks like 2FA authenticator, it justs sends the captcha so the user solves it, it gets the correct cookie and send it back to Flaresolverr. But that's only an idea.

**Comment by charly925** [comment]
>  Then, setup YGGcookie on Jackett (use its instructions) using the cookie header from your PC.

Could you detail how you're doing that (or provide a link) ? 
I have not find anything regarding this.

Thanks

**Comment by arnishow** [comment]
I was able to solve this issue using yggcookie and harvester. Ty @LeVraiRoiDHyrule 
Yggtorrent still not working though.

**Comment by Samhot** [comment]
I didn't change anything since the upgrade to 1.2.8 one month ago and it's working now !
