### ISSUE TITLE
SOCKS5 proxy not working

### ISSUE THREAD

**Issue by i3laze** [FlareSolverr/FlareSolverr#214]
Great news, that proxy feature is up.
I'm trying to forward Jackett with Flaresolverr through socks5 proxy (actually Tor).

I wonder if Jackett  v0.19.108 uses correct syntax for socks5...
Firefox with manual proxy settings (socks5 127.0.0.1:9050) does work.
```
c:\ProgramData\flaresolverr>flaresolverr
2021-10-31T18:41:51+03:00 INFO FlareSolverr v2.0.1
2021-10-31T18:41:51+03:00 INFO Testing web browser installation...
2021-10-31T18:41:55+03:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
2021-10-31T18:41:55+03:00 INFO Test successful
2021-10-31T18:41:55+03:00 INFO Listening on http://0.0.0.0:8191
2021-10-31T18:41:58+03:00 INFO REQ-1 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www.lostfilm.run/new","proxy":{"url":"socks5://127.0.0.1:9050"}}
2021-10-31T18:42:01+03:00 ERROR REQ-1 Unexpected error: Error: NS_ERROR_NET_RESET at https://www.lostfilm.run/new
2021-10-31T18:42:02+03:00 ERROR REQ-1 Error: Unable to process browser request. Error: NS_ERROR_NET_RESET at https://www.lostfilm.run/new
2021-10-31T18:42:02+03:00 INFO REQ-1 Response in 3.629 s
```

**Comment by ngosang** [comment]
SOCKS proxy should work but I never tested it.
Are you able to configure the proxy in your web browser (Firefox or Chrome)? Does it work?

**Comment by i3laze** [comment]
Yeah, as I mentioned, Firefox.eve configured with this exact socks5 proxy does open pages (which are restricted without proxy).

Please, do some tests with Flaresolverr vs SOCKS5.

**Comment by ngosang** [comment]
Fixed in v2.0.2

**Comment by Hyperz** [comment]
> 
> 
> Fixed in v2.0.2

Doesn't look like it fixed it unfortunately. I'm still getting the same error using a socks5 proxy despite that proxy working fine with Python's `aiohttp`. Does `network.proxy.http` etc need to be set when using a socks proxy? In Firefox I leave those blank. I also don't see `network.proxy.socks_version` getting set, which I'd assume required. It's probably a good idea to do a `switch` on the proxy URL's protocol and construct `proxyPrefs ` accordingly.

**Comment by ngosang** [comment]
I don't have a SOCKS5 proxy to test ATM. Feel free to play with the code and open a PR.

**Comment by Hyperz** [comment]
I'm not familiar with Node and I don't have a dev environment setup for it at the moment, sorry. You can get test proxies from places like http://free-proxy.cz/en/proxylist/country/all/socks5/ping/all, although not all of them work all the time.

At any rate, I was thing something along the lines of:
```javascript
const [protocol, ipAndPort] = proxy.url.split('://');
const [host, portStr] = ipAndPort.split(':');
const port = parseInt(portStr);

// Proxy configuration
let proxyPrefs = {
  "network.proxy.share_proxy_settings": true,
  "network.proxy.type": 1
}

switch (protocol) {
  case "http":
  case "https":
    proxyPrefs = {
      ...proxyPrefs,
      "network.proxy.ftp": host,
      "network.proxy.ftp_port": port,
      "network.proxy.http": host,
      "network.proxy.http_port": port,
      "network.proxy.ssl": host,
      "network.proxy.ssl_port": port
    };
    break;

  case "socks4":
  case "socks5":
    proxyPrefs = {
      ...proxyPrefs,
      "network.proxy.socks": host,
      "network.proxy.socks_port": port,
      "network.proxy.socks_version": (protocol == "socks4") ? 4 : 5,
      "network.proxy.socks_remote_dns": true
    };
    break;

  default:
    break;
}```

**Comment by i3laze** [comment]
Can't confirm the v2.0.2 fix worked either, sorry(
```
2021-11-01T20:18:10+03:00 INFO REQ-3 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www.lostfilm.run/new","proxy":{"url":"socks5://127.0.0.1:9050"}}
2021-11-01T20:18:17+03:00 ERROR REQ-3 Unexpected error: Error: <unknown error> at https://www.lostfilm.run/new
2021-11-01T20:18:18+03:00 ERROR REQ-3 Error: Unable to process browser request. Error: <unknown error> at https://www.lostfilm.run/new
2021-11-01T20:18:18+03:00 INFO REQ-3 Response in 7.61 s
```

You're free to test via my Tor SOCKS5 proxy for a while:
91.218.86.30:39050

**Comment by i3laze** [comment]
@ngosang , please unClose the issue.
You’re welcome to do some tests in spare time with my SOCKS5 proxy published above.

**Comment by i3laze** [comment]
@ngosang , up

**Comment by i3laze** [comment]
Just a quick workaround:
I've install a [DeleGate](http://ja.delegate.org/delegate/dg9.conf.shtml) win32-service as a HTTP-proxy:9080 frontend to my SOCSK5:9050.

**Comment by murmanskiy** [comment]
up, need fix it

**Comment by ngosang** [comment]
Fixed in FlareSolverr 2.1.0
It is working with Jackett too.
