### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by Zalatis** [FlareSolverr/FlareSolverr#235]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.0.2
* **Last working FlareSolverr version**: --
* **Operating system**: Windows 11 Pro (x64)
* **Are you using Docker**: No
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
* **Are you using a proxy or VPN?:** No
* **Are you using Captcha Solver:** No
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www3.yggtorrent.nz/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=seed

### Description

Launch "Test" using Jackett for YGGtorrent 

### Logged Error Messages

On FlareSolverr console it says : "Challenge solved"
But on Radarr it says that cookies are not valid : 

`Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 594
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 758
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61`

**Comment by pl77** [comment]
Same issue with me, but for Jackett: 

Flaresolverr v2.0.2
Jackett v0.20.95

```
Jackett.Common.IndexerException: Exception (1337x): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by pl77** [comment]
When I curl the destination URL from inside the Jackett container I get the following JSON: 

```JSON
{"status":"ok","message":"","startTimestamp":1638800203896,"endTimestamp":1638800207266,"version":"v2.0.2","solution":{"url":"https://1337x.to/cat/Movies/time/desc/1/","status":200,"headers":{"date":"Mon, 06 Dec 2021 14:16:46 GMT","content-type":"text/html","vary":"Accept-Encoding","x-frame-options":"DENY","cf-cache-status":"DYNAMIC","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","report-to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=TTmpqTSHBe1%2BF32f1xbtTFouJhwAa1c2M2nJtxEgZThiZAgOAVJI3QQuaZQ3X2stDb4VriULmtW2S%2BdrQecIEgRpQLcbG5lrjdwQs8rg0MnHk7JEekgrubEI3g%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","nel":"{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","server":"cloudflare","cf-ray":"6b96224a6a30f210-ARN","content-encoding":"br","alt-svc":"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400","x-firefox-spdy":"h2"},"response":"<!DOCTYPE html><html><head>\n<meta charset=\"utf-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<title>Download Movies Torrents | 1337x</title>\n<meta name=\"description\" content=\"Download latest Movies torrents in categories: DVD, Divx/Xvid, SVCD/VCD, Dubs/Dual Audio, HD, h.264/x264, Mp4, 3D, HEVC/x265, Bollywood, UHD\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"stylesheet\" href=\"/css/jquery-ui.css\">\n<link rel=\"stylesheet\" href=\"/css/icons.css\">\n<link rel=\"stylesheet\" href=\"/css/fancySelect.css\">\n<link rel=\"stylesheet\" href=\"/css/style10.2021-12-06-15.css\">\n<link rel=\"shortcut icon\" href=\"/favicon.ico\">\n<!--[if lt IE 9]><script src = \"/js/html5shiv.js\"></script><![endif]-->\n\n<script type=\"text/javascript\" id=\"antiClickjackJS\">\nif (self === top) {\nvar antiClickjack = document.getElementById(\"antiClickjack\");\nantiClickjack.parentNode.removeChild(antiClickjack);\n} else {\ntop.location = self.location;\n}\n</script>\n<script async=\"\" src=\"/cdn-cgi/challenge-platform/h/g/scripts/invisible.js\"></script><script async=\"\" src=\"https://jsc.adskeeper.com/1/3/1337x.to.1137329.es6.js\"></script><link rel=\"preconnect\" href=\"https://servicer.adskeeper.com\"></head>\n<body>\n<div class=\"mobile-menu\">\n<ul class=\"main-navigation\">\n<li class=\"active\"><a href=\"/home/\" title=\"Go to Home\">Home</a></li>\n<li><a href=\"/upload\" title=\"Upload Torrent File\">Upload</a></li>\n<li><a href=\"/rules\" title=\"Rules\">Rules</a></li>\n<li><a href=\"/contact\" title=\"Contact 1337x\">Contact</a></li>\n<li><a href=\"/about\" title=\"About us\">About us</a></li>\n</ul>\n\n<ul class=\"top-bar-nav\">\n<li><a href=\"/register\">Register</a></li>\n<li class=\"active\"><a href=\"/login\">Login</a></li>\n</ul>\n</div>\n<div class=\"top-bar\">\n<div class=\"container\">\n<ul class=\"top-bar-nav\">\n<li><a href=\"/register\">Register</a></li>\n<li class=\"active\"><a href=\"/login\">Login</a></li>\n</ul>\n</div>\n</div>\n<header>\n<div class=\"container\">\n<div class=\"clearfix\">\n<div class=\"logo\"><a href=\"/home/\"><img alt=\"logo\" src=\"/images/logo.svg\"></a></div>\n<a href=\"#\" class=\"navbar-menu\"><span></span><span></span><span></span></a>\n<div class=\"search-box\">\n<form id=\"search-form\" method=\"get\" action=\"/srch\" novalidate=\"true\">\n<input type=\"search\" placeholder=\"Search for torrents..\" id=\"autocomplete\" name=\"search\" class=\"ui-autocomplete-input form-control\" autocomplete=\"off\">\n<button type=\"submit\" class=\"btn btn-search\"><i class=\"flaticon-search\"></i><span>Search</span></button>\n</form>\n<ul class=\"ui-autocomplete ui-front ui-menu ui-widget ui-widget-content\" id=\"ui-id-1\" tabindex=\"0\" style=\"display: none;\"></ul></div>\n</div>\n<nav>\n<ul class=\"main-navigation\">\n<li class=\"active\"><a href=\"/home/\" title=\"Go to Home\">Home</a></li>\n<li><a href=\"/upload\" title=\"Upload Torrent File\">Upload</a></li>\n<li><a href=\"/rules\" title=\"Rules\">Rules</a></li>\n<li><a href=\"/contact\" title=\"Contact 1337x\">Contact</a></li>\n<li><a href=\"/about\" title=\"About us\">About us</a></li>\n</ul>\n</nav>\n</div>\n</header>\n<main class=\"container\">\n<div class=\"row\">\n<aside class=\"col-3 pull-right\">\n<div class=\"list-box\">\n<h2>Browse torrents</h2>\n<ul>\n<li><a href=\"/trending\" title=\"Trending Torrents\"><i class=\"flaticon-trending\"></i> Trending Torrents</a></li>\n<li><a href=\"/movie-library/1/\" title=\"Movie Library\"><i class=\"flaticon-movie-library\"></i> Movie library</a></li>\n<li><a href=\"/series-library/a/1/\" title=\"TV Library\"><i class=\"flaticon-tv-library\"></i> TV library</a></li>\n<li><a href=\"/new-episodes/day/1/\" title=\"New TV Episodes\"><i class=\"flaticon-tv\"></i> New TV Episodes</a></li>\n<li><a href=\"/top-100\" title=\"Top 100 Torrents\"><i class=\"flaticon-top\"></i> Top 100 Torrents</a></li>\n<li><a href=\"/cat/Anime/1/\" title=\"Anime\"><i class=\"flaticon-ninja-portrait\"></i> Anime</a></li>\n<li><a href=\"/cat/Apps/1/\" title=\"Applications\"><i class=\"flaticon-apps\"></i> Applications</a></li>\n<li><a href=\"/cat/Documentaries/1/\" title=\"Documentaries\"><i class=\"flaticon-documentary\"></i> Documentaries</a></li>\n<li><a href=\"/cat/Games/1/\" title=\"Games\"><i class=\"flaticon-games\"></i> Games</a></li>\n<li><a href=\"/cat/Movies/1/\" title=\"Movies\"><i class=\"flaticon-movies\"></i> Movies</a></li>\n<li><a href=\"/cat/Music/1/\" title=\"Movies\"><i class=\"flaticon-music\"></i> Music</a></li>\n<li><a href=\"/cat/Other/1/\" title=\"Others\"><i class=\"flaticon-other\"></i> Other</a></li>\n<li><a href=\"/cat/TV/1/\" title=\"Television\"><i class=\"flaticon-tv\"></i> Television</a></li>\n<li><a href=\"/cat/XXX/1/\" title=\"XXX\"><i class=\"flaticon-xxx\"></i> XXX</a></li>\n</ul>\n</div>\n<div class=\"list-box hidden-sm\">\n<h2>1337x Links</h2>\n<ul class=\"list\">\n<li><a target=\"_blank\" href=\"https://www.1337x-forum.eu/\"> 1337x Forum</a></li>\n<li><a target=\"_blank\" href=\"https://chat.1337x.to\"> 1337x Chat</a></li>\n<li><a target=\"_blank\" href=\"https://orangepix.is\">OrangePix</a></li>\n<li><a target=\"_blank\" href=\"https://njal.la\"> Njalla</a></li>\n<li><a target=\"_blank\" href=\"https://torrentz2.is\"> Torrentz2</a></li>\n<li><a target=\"_blank\" href=\"https://www.limetorrents.cc\"> Limetorrents</a></li>\n<li><a target=\"_blank\" href=\"https://www.torrentfunk.com\"> TorrentFunk</a></li>\n<li><a target=\"_blank\" href=\"https://www.torlock.com\"> Torlock</a></li>\n</ul>\n</div>\n</aside>\n<div class=\"col-9 page-content trending-torrent-explore\">\n<div class=\"box-info filter-list small-list\">\n<div class=\"box-info-heading clearfix no-bottom-radius\">\n<h2> Subcategories for Movies</h2>\n</div>\n<div class=\"box-info-detail\">\n<div class=\"black-box\">\n<ul class=\"clearfix\">\n<li><a title=\"3D\" href=\"/sub/66/0/\"><span class=\"icon\"><i class=\"flaticon-3d\"></i></span> 3D</a></li>\n<li><a title=\"Bollywood\" href=\"/sub/73/0/\"><span class=\"icon\"><i class=\"flaticon-divx\"></i></span> Bollywood</a></li>\n<li><a title=\"Divx/Xvid\" href=\"/sub/2/0/\"><span class=\"icon\"><i class=\"flaticon-divx\"></i></span> Divx/Xvid</a></li>\n<li><a title=\"Dubs/Dual Audio\" href=\"/sub/4/0/\"><span class=\"icon\"><i class=\"flaticon-video-dual-sound\"></i></span> Dubs/Dual Audio</a></li>\n<li><a title=\"DVD\" href=\"/sub/1/0/\"><span class=\"icon\"><i class=\"flaticon-dvd\"></i></span> DVD</a></li>\n<li><a title=\"h.264/x264\" href=\"/sub/54/0/\"><span class=\"icon\"><i class=\"flaticon-h264\"></i></span> h.264/x264</a></li>\n<li><a title=\"HD\" href=\"/sub/42/0/\"><span class=\"icon\"><i class=\"flaticon-hd\"></i></span> HD</a></li>\n<li><a title=\"HEVC/x265\" href=\"/sub/70/0/\"><span class=\"icon\"><i class=\"flaticon-hd\"></i></span> HEVC/x265</a></li>\n<li><a title=\"Mp4\" href=\"/sub/55/0/\"><span class=\"icon\"><i class=\"flaticon-mp4\"></i></span> Mp4</a></li>\n<li><a title=\"SVCD/VCD\" href=\"/sub/3/0/\"><span class=\"icon\"><i class=\"flaticon-svcd\"></i></span> SVCD/VCD</a></li>\n<li><a title=\"UHD\" href=\"/sub/76/0/\"><span class=\"icon\"><i class=\"flaticon-hd\"></i></span> UHD</a></li>\n</ul>\n</div>\n</div>\n</div>\n<div id=\"M713606ScriptRootC1137329_04289\"><div id=\"AdskeeperComposite1137329_04289\"></div></div>\n<script src=\"https://jsc.adskeeper.com/1/3/1337x.to.1137329.js\" async=\"\"></script>\n<script type=\"text/javascript\" src=\"//starkhelperidentifier.com/16/3c/43/163c43769401bee2c6f0831d393be424.js\"></script>\n<div class=\"box-info trending\">\n<div class=\"box-info-heading clearfix\">\n<h1><span class=\"featured-icon\"><i class=\"flaticon-movies\"></i></span> Movies Torrents download list </h1>\n</div>\n</div>\n<div class=\"featured-list\">\n<div class=\"table-list-wrap\">\n<table class=\"table-list table table-responsive table-striped\">\n<thead>\n<tr>\n<th class=\"coll-1 name\">name</th>\n<th class=\"coll-2\">se</th>\n<th class=\"coll-3\">le</th>\n<th class=\"coll-date\">time</th>\n <th class=\"coll-4\"><span class=\"size\">size</span> <span class=\"info\">info</span></th>\n<th class=\"coll-5\">uploader</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/76/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076389/The-Wishing-Tree-2021-2160p-WEB-DL-DD5-1-HEVC-EVO-TGx/\">The.Wishing.Tree.2021.2160p.WEB-DL.DD5.1.HEVC-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:14pm</td>\n<td class=\"coll-4 size mob-uploader\">7.4 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/76/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076388/Ray-Jrs-Legit-Paper-2021-2160p-WEB-DL-AAC2-0-HEVC-EVO-TGx/\">Ray.Jrs.Legit.Paper.2021.2160p.WEB-DL.AAC2.0.HEVC-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:14pm</td>\n<td class=\"coll-4 size mob-uploader\">6.9 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/70/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076385/Dune-2021-1080p-DS4K-SDR-BluRay-Hindi-Eng-DTS-AC3-x265-PeruGuy/\">Dune.(2021).1080p.DS4K.SDR.BluRay.[Hindi+Eng].DTS-AC3.x265-PeruGuy</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:13pm</td>\n<td class=\"coll-4 size mob-uploader\">11.5 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/PeruGuy/\">PeruGuy</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076384/Maya-and-Her-Lover-2021-1080p-WEB-DL-AAC2-0-H-264-EVO-TGx/\">Maya.and.Her.Lover.2021.1080p.WEB-DL.AAC2.0.H.264-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:12pm</td>\n<td class=\"coll-4 size mob-uploader\">5.1 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/76/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076383/Maya-and-Her-Lover-2021-2160p-WEB-DL-AAC2-0-HEVC-EVO-TGx/\">Maya.and.Her.Lover.2021.2160p.WEB-DL.AAC2.0.HEVC-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:11pm</td>\n<td class=\"coll-4 size mob-uploader\">9.0 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076381/Ray-Jrs-Legit-Paper-2021-1080p-WEB-DL-AAC2-0-H-264-EVO-TGx/\">Ray.Jrs.Legit.Paper.2021.1080p.WEB-DL.AAC2.0.H.264-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:09pm</td>\n<td class=\"coll-4 size mob-uploader\">3.2 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076380/The-Wishing-Tree-2021-1080p-WEB-DL-DD5-1-H-264-EVO-TGx/\">The.Wishing.Tree.2021.1080p.WEB-DL.DD5.1.H.264-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:09pm</td>\n<td class=\"coll-4 size mob-uploader\">4.2 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076379/Detective-Dee-and-The-Red-Eye-2021-CHINESE-1080p-WEB-DL-x264-Mkvking/\">Detective.Dee.and.The.Red.Eye.2021.CHINESE.1080p.WEB-DL.x264-Mkvking</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:07pm</td>\n<td class=\"coll-4 size mob-vip\">1.2 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 vip\"><a href=\"/user/bone111/\">bone111</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076378/The-Handler-2021-1080p-WEB-DL-AAC2-0-H-264-EVO-TGx/\">The.Handler.2021.1080p.WEB-DL.AAC2.0.H.264-EVO[TGx]</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">2:07pm</td>\n<td class=\"coll-4 size mob-uploader\">4.1 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TGxGoodies/\">TGxGoodies</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/54/0/\" class=\"icon\"><i class=\"flaticon-h264\"></i></a><a href=\"/torrent/5076373/Three-on-a-Match-1932-Mervyn-LeRoy-Crime-720p-x264-Classics/\">Three.on.a.Match.1932.(Mervyn.LeRoy-Crime).720p.x264-Classics</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:54pm</td>\n<td class=\"coll-4 size mob-uploader\">919.8 MB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/sulagyn62/\">sulagyn62</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076370/The-Suitor-1962-Pierre-Etaix-Comedy-1080p-BRRip-x264-Classics/\">The.Suitor.1962.(Pierre.Etaix-Comedy).1080p.BRRip.x264-Classics</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:48pm</td>\n<td class=\"coll-4 size mob-uploader\">1.2 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/sulagyn62/\">sulagyn62</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076367/Tant-Quon-a-la-Sante-1966-Pierre-Etaix-1080p-BRRip-x264-Classics/\">Tant.Quon.a.la.Sante.1966.(Pierre.Etaix).1080p.BRRip.x264-Classics</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:43pm</td>\n<td class=\"coll-4 size mob-uploader\">992.3 MB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/sulagyn62/\">sulagyn62</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076363/Rupture-1961-Pierre-Etaix-Comedy-Short-1080p-BRRip-x264-Classics/\">Rupture.1961.(Pierre.Etaix-Comedy-Short).1080p.BRRip.x264-Classics</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:37pm</td>\n<td class=\"coll-4 size mob-uploader\">171.5 MB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/sulagyn62/\">sulagyn62</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076360/Heureux-Anniversaire-1962-Pierre-Etaix-Short-1080p-BRRip-x264-Classics/\">Heureux.Anniversaire.1962.(Pierre.Etaix-Short).1080p.BRRip.x264-Classics</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:32pm</td>\n<td class=\"coll-4 size mob-uploader\">189.7 MB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/sulagyn62/\">sulagyn62</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076352/Deadly-Cuts-2021-1080p-WEBRip-x264/\">Deadly.Cuts.2021.1080p.WEBRip.x264</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:23pm</td>\n<td class=\"coll-4 size mob-uploader\">1.7 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TheMorozko/\">TheMorozko</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/73/0/\" class=\"icon\"><i class=\"flaticon-divx\"></i></a><a href=\"/torrent/5076351/Zila-Sangrur-2021-x264-720p-WebHD-Esub-AAC-Punjabi-THE-GOPI-SAHI/\">Zila Sangrur 2021 x264 720p WebHD Esub AAC Punjabi THE GOPI SAHI</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:22pm</td>\n<td class=\"coll-4 size mob-uploader\">1.1 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/Thegopisahi/\">Thegopisahi</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/54/0/\" class=\"icon\"><i class=\"flaticon-h264\"></i></a><a href=\"/torrent/5076350/The-Mitchells-vs-the-Machines-2021-BRRip-x264-ION10/\">The.Mitchells.vs.the.Machines.2021.BRRip.x264-ION10</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:22pm</td>\n<td class=\"coll-4 size mob-uploader\">1.0 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TheMorozko/\">TheMorozko</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/54/0/\" class=\"icon\"><i class=\"flaticon-h264\"></i></a><a href=\"/torrent/5076349/The-Card-Counter-2021-BRRip-x264-ION10/\">The.Card.Counter.2021.BRRip.x264-ION10</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:20pm</td>\n<td class=\"coll-4 size mob-uploader\">1.1 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TheMorozko/\">TheMorozko</a></td>\n</tr>\n <tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076348/The-Curious-Tale-of-Mr-Guo-2021-Chinese-HDRip-HC-1080p-ACC-2-0-H264/\">The Curious Tale of Mr Guo 2021 Chinese HDRip HC 1080p ACC 2.0 H264</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:18pm</td>\n<td class=\"coll-4 size mob-vip\">1,000.8 MB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 vip\"><a href=\"/user/bone111/\">bone111</a></td>\n</tr>\n<tr>\n<td class=\"coll-1 name\"><a href=\"/sub/42/0/\" class=\"icon\"><i class=\"flaticon-hd\"></i></a><a href=\"/torrent/5076346/Red-Snow-2021-1080p-WEBRip-x264/\">Red.Snow.2021.1080p.WEBRip.x264</a></td>\n<td class=\"coll-2 seeds\">0</td>\n<td class=\"coll-3 leeches\">0</td>\n<td class=\"coll-date\">1:14pm</td>\n<td class=\"coll-4 size mob-uploader\">1.5 GB<span class=\"seeds\">0</span></td>\n<td class=\"coll-5 uploader\"><a href=\"/user/TheMorozko/\">TheMorozko</a></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div class=\"pagination\">\n<ul>\n<li class=\"active\"><a href=\"/cat/Movies/1/\">1</a></li>\n<li><a href=\"/cat/Movies/2/\">2</a></li>\n<li><a href=\"/cat/Movies/3/\">3</a></li>\n<li><a href=\"/cat/Movies/4/\">4</a></li>\n<li><a href=\"/cat/Movies/5/\">5</a></li>\n<li><a href=\"/cat/Movies/6/\">6</a></li>\n<li><a href=\"/cat/Movies/7/\">7</a></li>\n<li><a href=\"/cat/Movies/2/\">&gt;&gt;</a></li>\n<li class=\"last\"><a href=\"/cat/Movies/150/\">Last</a></li>\n</ul>\n</div>\n</div>\n</div>\n</div>\n</main>\n<footer>\n<div class=\"bitcoin\">\n<div class=\"bitcoin-icon-wrap\">\n<span class=\"bitcoin-icon\"><i class=\"flaticon-bitcoin red\"></i></span>\n</div>\n<span class=\"bitcoin-text\"><span>Bitcoin Donate: </span><a href=\"bitcoin:3Qpdm4ckJ64irx1Nuyw9ZCCvc2qxoqkuBY\">3Qpdm4ckJ64irx1Nuyw9ZCCvc2qxoqkuBY</a></span>\n</div>\n<a class=\"scroll-top\" href=\"#\"><i class=\"flaticon-up\"></i></a>\n<ul>\n<li><a href=\"/\">Home</a></li>\n<li class=\"active\"><a href=\"/home/\">Full Home Page</a></li>\n<li><a href=\"/contact\">Dmca</a></li>\n<li><a href=\"/contact\">Contact</a></li>\n</ul>\n<p class=\"info\">1337x 2007 - 2021</p>\n</footer>\n<script src=\"/js/jquery-1.11.0.min.js\"></script>\n<script src=\"/js/jquery-ui.js\"></script>\n<script src=\"/js/auto-searchv2.js\"></script>\n<script src=\"/js/fancySelect.js\"></script>\n<script src=\"/js/main.js\"></script>\n<script>\n\n  $(window).load(function() {\n    $('.select').fancySelect();\n  });\n</script>\n<script type=\"text/javascript\">(function(){window['__CF$cv$params']={r:'6b96224a6a30f210',m:'TkLJ98TLMWKssYB5WFXYhJS129HyX93G6Mce3XC2ZFI-1638800206-0-AX4dHfqXj01PziO2jHcJE8gi1Ncnh+5O0P306tDKjsPpn9x1FLNEyfscSfNL4hUfXU45RN4Lv+de4QObMUNLOkezHhLCoU2I68ebS8X3CHjqMYBPCaqzI3vgaJ8zzPfj3MyxSY+3oDcNQfdZc4mlXjE=',s:[0x85e4c4be4c,0x0b992f0651],u:'/cdn-cgi/challenge-platform/h/g'}})();</script>\n<span role=\"status\" aria-live=\"assertive\" aria-relevant=\"additions\" class=\"ui-helper-hidden-accessible\"></span></body></html>","cookies":[],"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"}}
```

At the end it does indeed show that FlareSolverr is not sending any cookies with the response: 

```JSON
"cookies":[]
```

**Comment by pl77** [comment]
I will give it a shot and report back.

**Comment by EdRawaled** [comment]
Hello
How to disable IPv6 for containers?

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by LeVraiRoiDHyrule** [comment]
Hi,
I'm having the exact same issue. But I didn't find any solution so far.
Jackett was running natively and Flaresolverr on Docker. Some people said it could be because of ipv6. So I moved Jackett to Docker too so I can block ipv6 to both containers (using `net.ipv6.conf.all.disable_ipv6 = true` for both containers).
But the same issue happens again.

Here are my logs:
```
FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

Is there a solution ? Everything I found on the flaresolverr and jackett github didn't work so far.

**Comment by ilike2burnthing** [comment]
If you're not using a proxy for Jackett, then I don't know. Provide debug FlareSolverr logs - https://github.com/FlareSolverr/FlareSolverr#environment-variables

In the mean time, switch to using yggcookie instead.

**Comment by LeVraiRoiDHyrule** [comment]
> 

Hi,

I'm not using any proxy.

Here are my FlareSolverr logs:
```
2021-12-12T13:25:07+00:00 INFO FlareSolverr v2.0.2,
2021-12-12T13:25:07+00:00 DEBUG Debug log enabled,
2021-12-12T13:25:07+00:00 INFO Testing web browser installation...,
2021-12-12T13:25:07+00:00 DEBUG FlareSolverr user home directory is OK: /home/node,
2021-12-12T13:25:07+00:00 DEBUG Launching web browser...,
2021-12-12T13:25:14+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0,
2021-12-12T13:25:14+00:00 INFO Test successful,
2021-12-12T13:25:14+00:00 INFO Listening on http://0.0.0.0:8191,
2021-12-12T13:26:56+00:00 INFO REQ-1 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www3.yggtorrent.re/"},
2021-12-12T13:26:56+00:00 DEBUG REQ-1 Launching web browser...,
2021-12-12T13:27:08+00:00 DEBUG REQ-1 Navigating to... https://www3.yggtorrent.re/,
2021-12-12T13:27:12+00:00 INFO REQ-1 Cloudflare detected,
2021-12-12T13:27:12+00:00 INFO REQ-1 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.,
2021-12-12T13:27:12+00:00 INFO REQ-1 Response in 16.68 s,
2021-12-12T13:27:28+00:00 INFO REQ-2 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www3.yggtorrent.re/"},
2021-12-12T13:27:28+00:00 DEBUG REQ-2 Launching web browser...,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Navigating to... https://www3.yggtorrent.re/,
2021-12-12T13:27:35+00:00 INFO REQ-2 Cloudflare detected,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:35+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:36+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:36+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:36+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:36+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:39+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:39+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:39+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:39+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:40+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:40+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:40+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:40+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:41+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:41+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:41+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:41+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:42+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:42+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:42+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:42+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:43+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.,
2021-12-12T13:27:43+00:00 DEBUG REQ-2 Challenge element is visible,
2021-12-12T13:27:43+00:00 DEBUG REQ-2 Found challenge element again,
2021-12-12T13:27:43+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...,
2021-12-12T13:27:44+00:00 DEBUG REQ-2 Unexpected error: Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id callFunctionOn@chrome://remote/content/cdp/domains/content/Runtime.jsm:218:15,
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25,
receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45,
2021-12-12T13:27:44+00:00 DEBUG REQ-2 Validating HTML code...,
2021-12-12T13:27:44+00:00 INFO REQ-2 Challenge solved,
2021-12-12T13:27:44+00:00 DEBUG REQ-2 Reloading the page,
2021-12-12T13:27:45+00:00 INFO REQ-2 Response in 16.382 s
```

I tried YGGcookie too. It works for a few days, but then ends up on this error in Jackett:
```
FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 594
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```
And this error in Flaresolverr:
```

2021-12-12T13:29:40+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:40+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:40+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:41+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:41+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:41+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:41+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:43+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:43+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:43+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:43+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:44+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:44+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:44+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:44+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:45+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:45+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:45+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:45+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:46+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:46+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:46+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:46+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:47+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:47+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:47+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:47+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:48+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:48+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:48+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:48+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:49+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:49+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:49+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:49+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:50+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:50+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:50+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:50+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:51+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:51+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:51+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:51+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:53+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:53+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:53+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:53+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:55+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:55+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:55+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:55+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:56+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:56+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:56+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:56+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:57+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:57+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:57+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:57+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:58+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:58+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:58+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:58+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:29:59+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:29:59+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:29:59+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:29:59+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:00+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:00+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:00+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:00+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:01+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:01+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:01+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:01+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:02+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:02+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:02+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:02+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:03+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:03+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:03+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:03+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:04+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:04+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:04+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:04+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:05+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:05+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:05+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:05+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:06+00:00 DEBUG REQ-3 Javascript challenge element '#trk_jschal_js' detected.

2021-12-12T13:30:06+00:00 DEBUG REQ-3 Challenge element is visible

2021-12-12T13:30:06+00:00 DEBUG REQ-3 Found challenge element again

2021-12-12T13:30:06+00:00 DEBUG REQ-3 Waiting for Cloudflare challenge...

2021-12-12T13:30:07+00:00 ERROR REQ-3 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)

2021-12-12T13:30:07+00:00 INFO REQ-3 Response in 82.245 s

2021-12-12T13:30:07+00:00 DEBUG REQ-3 Unexpected error: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

2021-12-12T13:30:07+00:00 DEBUG REQ-3 Validating HTML code...

2021-12-12T13:30:07+00:00 ERROR REQ-3 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.
```

**Comment by ngosang** [comment]
Fixed in FlareSolverr 2.1.0

**Comment by tcheronneau** [comment]
I've tested with FlareSolverr 2.1.0 and I still have this issue.

**Comment by icuthere** [comment]
I had the cookies not valid problem.  I was running Jacket on a seedbox (ultraseedbox) and flaresolverr on a dedicated ubuntu in a container.  I could run flaresolverr test successfully via curl commands on both.  But in Jackett I got the cookie invalid error.  

What solved this for me was moving jackett to the same dedicated server as the flaresolverr .  Both are in containers.  Now my seedbox, using radarr calls the dedicated server for index searches etc.  I happened to have an extra dedicated where I could do this, luckily.

**Comment by serranomorante** [comment]
> I had the cookies not valid problem. I was running Jacket on a seedbox (ultraseedbox) and flaresolverr on a dedicated ubuntu in a container. I could run flaresolverr test successfully via curl commands on both. But in Jackett I got the cookie invalid error.
> 
> What solved this for me was moving jackett to the same dedicated server as the flaresolverr . Both are in containers. Now my seedbox, using radarr calls the dedicated server for index searches etc. I happened to have an extra dedicated where I could do this, luckily.

My setup is exactly like yours. I also have an extra dedicated server but moving Jackett to another IP would be problematic for me.
In the end, I had to solve this by using an alternate site link for **https://kickasstorrents.to -> https://kickasstorrents.unblockninja.com** on Jackett settings. This seems like a hacky fix for me. I want the original site.
I also think there are sites that don't have alternative links.

**Comment by realivanjx** [comment]
still has this with the current master build (with Dockerfile)

**Comment by realivanjx** [comment]
running on raspberry pi 4 arm64 if that matters
