### ISSUE TITLE
[mteamtp] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.

### ISSUE THREAD

**Issue by log-time** [FlareSolverr/FlareSolverr#414]
[jackett-m-team.txt](https://github.com/FlareSolverr/FlareSolverr/files/9034339/m-team.txt)
[FlareSolverr.txt](https://github.com/FlareSolverr/FlareSolverr/files/9037302/20220704.txt)

**Comment by log-time** [comment]
[20220704.txt](https://github.com/FlareSolverr/FlareSolverr/files/9037296/20220704.txt)

**Comment by garfield69** [comment]
So the flow is that the login.php has a form that actioned a POST to takelogin.php which on successful login returns the index.php page which flaresolverr chokes on since it is not a challenge. The question is why did flaresolverr think there was a cloudflare page to process?

**Comment by garfield69** [comment]
for testing, you get the same issue with flaresolverr by using the jackett mteamtp config and using an invalid username/password

**Comment by log-time** [comment]
但是我的用户名和密码是有效的，在web端已正常登陆

**Comment by log-time** [comment]
你的意思是，我使用错误的用户名和密码测试下？

**Comment by garfield69** [comment]
@log-time No no. ;-) 
I was simply reporting that if the flaresolverr team wanted to test  this issue for themselves, in order to do code analysis, they could replicate the issue without having an account on mteamtp.
Just by using the jackett config with an dummy user and password they can test flaresolverr and get the same error .

**Comment by log-time** [comment]
`2022-07-04T15:21:51+08:00 INFO REQ-1 Response in 5.975 s
2022-07-04T15:57:03+08:00 INFO REQ-2 Incoming request => POST /v1 body: {"postData":"username=112233&password=123456","maxTimeout":55000,"cmd":"request.post","url":"https://kp.m-team.cc/takelogin.php"}
2022-07-04T15:57:03+08:00 DEBUG REQ-2 Creating new session...
2022-07-04T15:57:03+08:00 DEBUG REQ-2 Launching web browser...
2022-07-04T15:57:04+08:00 DEBUG REQ-2 Navigating to... https://kp.m-team.cc/takelogin.php
2022-07-04T15:57:09+08:00 DEBUG REQ-2 <html><head></head><body></body></html>
2022-07-04T15:57:09+08:00 INFO REQ-2 Cloudflare detected
2022-07-04T15:57:09+08:00 DEBUG REQ-2 No challenge element detected.
2022-07-04T15:57:09+08:00 INFO REQ-2 Cloudflare Error: No challenge selectors found, unable to proceed.

2022-07-04T15:57:09+08:00 INFO REQ-2 Response in 5.727 s`

**Comment by log-time** [comment]
以上是我使用jackett的mteamtp模板，在输入错误的用户名和密码的情况下得到的log

**Comment by garfield69** [comment]
@log-time  Yes, exactly.
Whether you succeed to login or fail to login, the flaresolverr issue is the same.
the flaresolverr team can test this for themselves using the visual studio SDK and test the code in debug mode to trace the code steps and results.
Hopefully they can use this information to fix the code, without having an account on mteamtp ;-)

**Comment by youngshook** [comment]
same issue

**Comment by TinPoChan** [comment]
Same here

**Comment by BBshinya** [comment]
Same here

**Comment by xztxy** [comment]
添加不了馒头的，可以先同docker的环境下安装docker版本的firefox浏览器添加，实际测试，这种可以添加，同样适用于一些其他无法添加的站点。

**Comment by TinPoChan** [comment]
> 

能詳細說明一下嗎? 謝謝

**Comment by JiaxuanShen** [comment]
Same here

**Comment by 1960697431** [comment]
same here

**Comment by sungamma** [comment]
我部署了docker版本的chrome，登入m-team。复制了cookies到mteamtp2FA，管用了一两天，又断连了。

**Comment by garfield69** [comment]
@sungamma  can you provide the download link to the docker chrome you used?
@1960697431 can you provide the download link to the firefox you used?  
I want to update our wiki with these useful tools. Thanks.

**Comment by sungamma** [comment]
@garfield69  oldiy/chrome-novnc but it work only two days, and now it cannot work now

**Comment by garfield69** [comment]
>and now it cannot work now

did you get a new 2fa code as well as the fresh cookie from your chrome docker session to use with the mteamp indexer config?

**Comment by sungamma** [comment]
YES, I had to login with the new 2fa code a few miniutes ago, and copy the cookie to the jackett's mteap2fa. But it don't work. The jackett tell me "Exception (mteamtp2fa): Login Failed, got redirected.: Parse error"

**Comment by TinPoChan** [comment]
Neeeed heeeeelp 😢

**Comment by hitboxr** [comment]
Same issue with the SportsCult indexer:

```2022-07-21T16:43:46-07:00 INFO FlareSolverr v2.2.4
2022-07-21T16:43:46-07:00 INFO Testing web browser installation...
2022-07-21T16:43:48-07:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
2022-07-21T16:43:48-07:00 INFO Test successful
2022-07-21T16:43:48-07:00 INFO Listening on http://0.0.0.0:8191
2022-07-21T16:44:18-07:00 INFO REQ-1 Incoming request => POST /v1 body: {"postData":"uid=(userid)*********&pwd=(pass)********","maxTimeout":55000,"cmd":"request.post","url":"https://sportscult.org/index.php?page=login"}
2022-07-21T16:44:22-07:00 INFO REQ-1 Cloudflare detected
2022-07-21T16:44:23-07:00 INFO REQ-1 Cloudflare Error: No challenge selectors found, unable to proceed.
2022-07-21T16:44:23-07:00 INFO REQ-1 Response in 4.992 s```

Same behavior with an invalid user/pass as well, just like m-team above.

**Comment by ChestnutHeng** [comment]
same here

**Comment by jassysth** [comment]
same here

**Comment by FlameSky-S** [comment]
same here

**Comment by ngosang** [comment]
Fixed in:
FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

**Comment by Shurelol** [comment]
I have update FlareSolverr and Jackett to the latest version but the problem is still exists.
![image](https://user-images.githubusercontent.com/16237201/182003541-c7fb0a4e-88dd-4a65-9f48-bdc6a1241cfe.png)


> Fixed in: FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5 Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

**Comment by ngosang** [comment]
@Shurelol Could you provide the URL from the logs?

**Comment by Shurelol** [comment]
> @Shurelol Could you provide the URL from the logs?

![image](https://user-images.githubusercontent.com/16237201/182003624-59e27678-cfac-4774-b4aa-100cc04e1c7c.png)

**Comment by hitboxr** [comment]
> I have update FlareSolverr and Jackett to the latest version but the problem is still exists. ![image](https://user-images.githubusercontent.com/16237201/182003541-c7fb0a4e-88dd-4a65-9f48-bdc6a1241cfe.png)
> 
> > Fixed in: FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5 Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

Can confirm the issue is also still present for SportsCult with FlareSolverr v2.2.5 and Jackett v0.20.1496:

```
2022-07-30T16:58:50-07:00 INFO FlareSolverr v2.2.5
2022-07-30T16:58:50-07:00 INFO Testing web browser installation...
2022-07-30T16:58:52-07:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-07-30T16:58:52-07:00 INFO Test successful
2022-07-30T16:58:52-07:00 INFO Listening on http://0.0.0.0:8191
2022-07-30T16:59:07-07:00 INFO REQ-1 Incoming request => POST /v1 body: {"postData":"uid=asdf&pwd=1234","maxTimeout":55000,"cmd":"request.post","url":"https://sportscult.org/index.php?page=login"}
2022-07-30T16:59:13-07:00 INFO REQ-1 Cloudflare detected
2022-07-30T16:59:13-07:00 INFO REQ-1 Cloudflare Error: No challenge selectors found, unable to proceed.
2022-07-30T16:59:13-07:00 INFO REQ-1 Response in 5.941 s
```

**Comment by ngosang** [comment]
Fixed in 2.2.6
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.6

**Comment by Shurelol** [comment]
FlareSolverr v2.2.6 works! fantastic job！
![image](https://user-images.githubusercontent.com/16237201/182033301-e31eb3c2-3e2c-411c-ab3d-21b717f55c55.png)
![image](https://user-images.githubusercontent.com/16237201/182033308-b6627c44-8b4b-4f76-b103-1674cae99014.png)



> Fixed in 2.2.6 https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.6

**Comment by hitboxr** [comment]
> Fixed in 2.2.6 https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.6

Worked for SportsCult as well. Thanks for the quick fix @ngosang

**Comment by TinPoChan** [comment]
Thanks for updating!

**Comment by ExorDG** [comment]
I am getting the same error:

`2023-01-03T20:51:50-06:00 INFO REQ-13 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&search="}
2023-01-03T20:51:53-06:00 INFO REQ-13 Cloudflare detected
2023-01-03T20:51:54-06:00 INFO REQ-13 Cloudflare Error: No challenge selectors found, unable to proceed.
2023-01-03T20:51:54-06:00 INFO REQ-13 Response in 3.609 s
2023-01-03T20:51:54-06:00 INFO REQ-14 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://privatehd.to/api/v1/jackett/torrents?in=1&type=0&search="}
2023-01-03T20:51:57-06:00 INFO REQ-14 Cloudflare detected
2023-01-03T20:51:58-06:00 INFO REQ-14 Cloudflare Error: No challenge selectors found, unable to proceed.
2023-01-03T20:51:58-06:00 INFO REQ-14 Response in 4.047 s`

I am running on FlareSolverr: v2.2.10 and Jackett: v0.20.2469.
