### ISSUE TITLE
[1337x] (testing) Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by vsin123** [FlareSolverr/FlareSolverr#443]
![image](https://user-images.githubusercontent.com/88284263/181996403-1575146d-c047-4dde-8e0c-2a96aa906165.png)

**Comment by ngosang** [comment]
Fixed in:
FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

**Comment by vsin123** [comment]
![image](https://user-images.githubusercontent.com/88284263/182002954-68e58c63-3a54-4b48-ab72-0b75f8ec73f8.png)

**Comment by vsin123** [comment]
I have updated to the latest version, but the error still occurs

**Comment by ngosang** [comment]
I'm going to close again because there are workarounds:

- No Cloudflare => https://1337x.unblockninja.com/
- FlareSolverr works => https://1337x.nocensor.world/
- FlareSolverr fails because they use the old challenge (will be changed in few days) => https://1337x.unblockit.ist/

**Comment by ngosang** [comment]
FlareSolverr 2.2.6

**Comment by plexxman** [comment]
> I'm going to close again because there are workarounds:
> 
> * No Cloudflare => https://1337x.unblockninja.com/
> * FlareSolverr works => https://1337x.nocensor.world/
> * FlareSolverr fails because they use the old challenge (will be changed in few days) => https://1337x.unblockit.ist/

BT4G is still throwing this error and it is not in those sites.

**Comment by 362227** [comment]
https://sharemania.us/ same error
