### ISSUE TITLE
Unable to solve captcha

### ISSUE THREAD

**Issue by bozoweed** [FlareSolverr/FlareSolverr#694]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: none
- Operating system: windows
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no]no
- Are you using a Proxy: [yes/no]yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:https://yggtorrent.lol/
```

### Description

hi , when i want to unlock this page with FlareSolverr i get code 500

this is a really simple captcha , is made a challenger spinner then a button is appear we nee to click on it to verify we are a humain 

FlareSolver has detect the div ID but seem unable to solve it 

### Logged Error Messages

```text
2023-02-07 16:46:30 DEBUG    ReqId 16752 Launching web browser...
2023-02-07 16:46:30 DEBUG    ReqId 16752 Started executable: `C:\Users\Administrateur\appdata\roaming\undetected_chromedriver\chromedriver.exe` in a child process with pid: 4972
2023-02-07 16:46:30 DEBUG    ReqId 15988 Navigating to... https://www6.yggtorrent.lol/
2023-02-07 16:46:31 INFO     ReqId 15988 Challenge detected. Selector found: #challenge-spinner
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:46:31 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:46:41 DEBUG    ReqId 15988 Timeout waiting for selector
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:46:41 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:46:51 DEBUG    ReqId 15988 Timeout waiting for selector
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:46:52 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:47:02 DEBUG    ReqId 15988 Timeout waiting for selector
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:47:02 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:47:12 DEBUG    ReqId 15988 Timeout waiting for selector
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:47:12 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:47:22 DEBUG    ReqId 15988 Timeout waiting for selector
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for title: Just a moment...
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for title: DDOS-GUARD
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for selector: #cf-challenge-running
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for selector: .ray_id
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for selector: .attack-box
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for selector: #cf-please-wait
2023-02-07 16:47:22 DEBUG    ReqId 15988 Waiting for selector: #challenge-spinner
2023-02-07 16:47:26 ERROR    ReqId 16752 Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-02-07 16:47:26 DEBUG    ReqId 16752 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 55.0 seconds.', 'startTimestamp': 1675784790239, 'endTimestamp': 1675784846180, 'version': '3.0.2'}
2023-02-07 16:47:26 INFO     ReqId 16752 Response in 55.941 s
2023-02-07 16:47:26 INFO     ReqId 16752 86.201.34.81 POST http://xx.xx.xx.xx:8191/v1 500 Internal Server Error
```

**Comment by bozoweed** [comment]
befor you answer i replace my ip by xx.xx.xx.xx to not share it with all the world ^^

**Comment by GregoireDelorme** [comment]
Same issue.
Solvers are not implemented at the moment for the v3, right ?

**Comment by bozoweed** [comment]
so what is the version i should used for haveing a solver ? is the name of the software .... falreSOLVER .... not proxy_without_ANY_SOLVER ..... that a was a big joke ...

**Comment by ilike2burnthing** [comment]
FlareSolverr solves Cloudflare challenges (hence the name), not captchas. Initially (v1) there was some captcha solver support, and plans to expand it, but it didn't work properly and so was removed. The hope is to reintroduce it at a later point.

As for this specific issue, not sure if it needs looked into further, so I'll leave it open for now.

**Comment by bozoweed** [comment]
thas was a cloufare challange , juster after the spinner i have a button to click to say i'm human , juste because i have put flaresolver on my dedicated server , but if put it on my pc at home that was working due tu ASN , i don't know if that can help you more

**Comment by LeonardMeyer** [comment]
I have the same issue on yggtorrent. No captcha per say but a Google checkbox.

**Comment by xyko0** [comment]
Hi, +1 same issue here 😞 : 
![image](https://user-images.githubusercontent.com/52315700/219400050-c873c6e4-5c11-4677-be9d-06cf33d2723c.png)

**Comment by screamjojo** [comment]
Same issue :(

**Comment by Nackophilz** [comment]
Same here, no work anymore on ygg because of the button (human verification)

**Comment by NathanFichefet** [comment]
Same :/

**Comment by bozoweed** [comment]
yes that was the real trouble, but seem no fiix for now unless use FlareSolver with home ip and without any proxy server or vpn to keep home ip, only ASN of dedicated hoster got this shit

**Comment by xyko0** [comment]
Hi, seems like problem is solved right ? 
Jackett works with YGG again

**Comment by NathanFichefet** [comment]
Yes I tried it and it works now

**Comment by D4rk56** [comment]
Yes works now

**Comment by bozoweed** [comment]
seem work yes, need to wait one or 2 day to confirm, maybe my jacket or flaresolver have saved the oldest validate cookie , in few hour we have the answer

**Comment by bozoweed** [comment]
hum no thing have been change on the project , i think they haven't been solved by FlareSolverr but only because the 'captcha' have been change may be , need to investigate

**Comment by xcybermanx** [comment]
Not work after YGG Disable Protection always Error :

2023-02-20 12:07:48 INFO     Test successful
2023-02-20 12:07:49 INFO     Serving on http://0.0.0.0:8191
2023-02-20 12:16:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 200000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date'}
2023-02-20 12:16:37 INFO     Challenge detected. Title found: Just a moment...
2023-02-20 12:19:54 ERROR    Error: Error solving the challenge. Timeout after 200.0 seconds.
2023-02-20 12:19:54 INFO     Response in 205.005 s
2023-02-20 12:19:54 INFO     172.18.0.2 POST http://flaresolverr:8191/v1 500 Internal Server Error
2023-02-20 12:46:08 INFO     Incoming request => POST /v1 body: {'maxTimeout': 200000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?
category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date'}
2023-02-20 12:46:11 INFO     Challenge detected. Title found: Just a moment...
2023-02-20 12:49:29 ERROR    Error: Error solving the challenge. Timeout after 200.0 seconds.
2023-02-20 12:49:29 INFO     Response in 201.165 s
2023-02-20 12:49:29 INFO     172.18.0.2 POST http://flaresolverr:8191/v1 500 Internal Server Error
2023-02-20 13:18:01 INFO     Incoming request => POST /v1 body: {'maxTimeout': 200000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date'}
2023-02-20 13:18:12 INFO     Challenge detected. Title found: Just a moment...
2023-02-20 13:21:31 ERROR    Error: Error solving the challenge. Timeout after 200.0 seconds.
2023-02-20 13:21:31 INFO     Response in 209.621 s
2023-02-20 13:21:31 INFO     172.18.0.2 POST http://flaresolverr:8191/v1 500 Internal Server Error

**Comment by estikf** [comment]
I am still having the same "500 Internal Server Error" issue, started on thursday. Using docker image v3.0.2 on both windows and linux. The same image was working last week. Could cloudflare have increased their security?

**Comment by xyko0** [comment]
Weird, I'm not having any issue anymore.
Did you try to upgrade / relaunch every app ?

**Comment by LeonardMeyer** [comment]
Still the same issue for me too on 3.0.2 with Prowlarr 1.2.2.2699.

```
[v1.2.2.2699] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [500:InternalServerError] [POST] at [http://flaresolverr:xxxx/v1]
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by bozoweed** [comment]
> Weird, I'm not having any issue anymore. Did you try to upgrade / relaunch every app ?

that wasn't solved by FlareSolver but only due to ASN that was trusted or not by YGG , so u can upgrade / reboot as much as u want nothing is gonna change , look the commit nothing has changed here

**Comment by xyko0** [comment]
> 

Yep, I was thinking about his cache in the other apps maybe... Why does it work for us and not for them then ?

**Comment by estikf** [comment]
@xyko0 Hi, can you try to access https://nowsecure.nl via Flaresolverr? Flaresolverr works for websites that are not protected by cloudflare. This example has protection and included in the tests of this repo. It is not working for me actually.

**Comment by macdis** [comment]
v3.0.2 Docker implementation, container on a vanilla bridge network, not behind a VPN.
```
$ curl -sL -X POST http://localhost:8191/v1 \
     -H 'Content-Type: application/json' \
     --data-raw \
     '{"cmd": "request.get","url": "https://nowsecure.nl","maxTimeout": 60000,"returnOnlyCookies": "true"}' \
     | jq
{
  "status": "error",
  "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.",
  "startTimestamp": 1677078730978,
  "endTimestamp": 1677078792192,
  "version": "3.0.2"
}
```

**Comment by VictorJ76** [comment]
I have the exact same logs as @macdis. Anything we can test to help on the investigation ? 
I'm with FlareSolverr 3.0.2 (no VPN). I use FlareSolver with YGG and can confirm my IP is not flagged.

```
docker run -d \
  -p 8191:8191 \
  --name=flaresolverr \
  -e LOG_LEVEL=info \
  -e LOG_HTML=true \
  -e maxTimeout=120000 \
  -e BROWSER_TIMEOUT=120000 \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
```

```
root@plex-v2:/home/victor# curl -sL -X POST http://localhost:8191/v1      -H 'Content-Type: application/json'      --data-raw      '{"cmd": "request.get","url": "https://nowsecure.nl","maxTimeout": 60000,"returnOnlyCookies": "true"}'      | jq
{
  "status": "error",
  "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.",
  "startTimestamp": 1677239947403,
  "endTimestamp": 1677240008045,
  "version": "3.0.2"
}
```

**Comment by GravuTrad** [comment]
again and again

https://github.com/FlareSolverr/FlareSolverr/issues/667

**Comment by user128747** [comment]
I also had this issue. I crossed another repo that added a few commits (newer undetected chrome + cloudflare related), I made an image of it and now everything works for me.
Here's the repo: https://github.com/furdarius/FlareSolverr/tree/patched_302
Build locally and use it instead then see if it changes anything.

**Comment by stb9** [comment]
> I also had this issue. I crossed another repo that added a few commits (newer undetected chrome + cloudflare related), I made an image of it and now everything works for me. Here's the repo: https://github.com/furdarius/FlareSolverr/tree/patched_302 Build locally and use it instead then see if it changes anything.

Nice. Confirmed working.

**Comment by Kise1223** [comment]
> 

It is working in my windows, but not working in my docker container.I don't know why.

**Comment by rix1337** [comment]
Might be fixed in #715

**Comment by ilike2burnthing** [comment]
v3.0.3 should resolve the issue. Retry a few times if it continues after updating.

**Comment by anonyme123** [comment]
Can confirm, everything working in 3.0.4! Many thanks :)
