### ISSUE TITLE
[dontorrent] (configuring) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by Tailor4** [FlareSolverr/FlareSolverr#713]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:first time I install flaresolver, never working. current version: {"msg": "FlareSolverr is ready!", "version": "3.0.2", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
- Operating system: docker on debian
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://dontorrent.ninja/ultimos
```

### Description

I cannot add dontorrent.ninja feed to jackett because of this error. Every time I try to add, same error msg.

I use the following compose:
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Madrid
    ports:
      - "8191:8191"
    restart: unless-stopped

### Logged Error Messages

```text
2023-02-23 10:26:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://dontorrent.ninja/ultimos'}
2023-02-23 10:26:42 INFO     Challenge detected. Title found: Just a moment...
2023-02-23 10:27:36 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-02-23 10:27:36 INFO     Response in 56.104 s
2023-02-23 10:27:36 INFO     192.168.2.1 POST https://XXXXXXXXXXXXXXXXX/v1 500 Internal Server Error
```

**Comment by ilike2burnthing** [comment]
Is Jackett also on Docker?

**Comment by Tailor4** [comment]
yes, on docker (image from Linuxserver Version v0.20.3269

**Comment by ilike2burnthing** [comment]
They share the same public IP? You're not using a proxy or VPN for either container, or your host device?

Have you disabled IPv6 for either the host or both containers?

**Comment by nebojsasandin** [comment]
@ilike2burnthing is it working for you? I'm getting the same error on any CloudFlare protected website for the past 2 days now, as if CloudFlare changed something.

**Comment by ilike2burnthing** [comment]
I don't get a Cloudflare challenge when using dontorrent, but otherwise FlareSolverr is working.

**Comment by adocampo** [comment]
Same here, dontorrent stop working, configured flaresolverr (I even didn't need flaresolverr until now).
 - Both jackett and flaresolverr are on the same docker-compose, so they share the same public IP address
 - No proxy or whatsoever to access the Internet, just docker --> host --> router --> Internet
 - I'm using IPv6 on the hosts (I have both, of course)

**Comment by Vctrsnts** [comment]
With the same problem with similar configuration ( error message is 500 Internal Server Error ):
- jackett on docker
- flaresolverr on docker

The configuration on flaresolverr ( in my case is this ):

  **flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "${PORT:-8191}:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid**

Thanks

**Comment by ilike2burnthing** [comment]
@adocampo disable IPv6

**Comment by GravuTrad** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/667

It's only the same issue.

**Comment by Crosus97** [comment]
Same here

**Comment by ilike2burnthing** [comment]
Is this a residential IP or are you using a VPS or seedbox?

**Comment by avt00** [comment]
I am experiencing the same issue. Both services are sharing the same public IP address in Germany, and they are both running from the same Docker Compose file.

**Comment by Razor648** [comment]
same issue with VPS IP in Danmark.

**Comment by pinpspinps** [comment]
Hello.
I have same issue for me

**Comment by adocampo** [comment]
> Is this a residential IP or are you using a VPS or seedbox?

It's my home's IP

**Comment by ivanjx** [comment]
i got same issue for a service with cloudflare protection. it used to work a few weeks ago (i dont use too much so i just noticed now). the logs keep saying `Waiting for title: Just a moment...`. even though i use a vpn, both my app and flaresolverr are on the same machine with the same public ip.

**Comment by CyberPoison** [comment]
Hello i have same issue on Cloud Computing at Hetzner.

**Comment by rix1337** [comment]
Fixed in #715

**Comment by CyberPoison** [comment]
> Fixed in #715

If it's fixed can some one merge and refresh the image on docker hub :-) it will be very nice :)

**Comment by rix1337** [comment]
Seems the main branch is not maintained. Last update was ~2 months ago.

**Comment by CyberPoison** [comment]
Yeah i also just have see that right now, maybe @ngosang is no more updating image on docker hub, but a question is remaining is there any other image on docker hub then are updated ? 
If no i can fork and deploy it to my docker hub account hoping the docker build is allready present on the repo, so just need to link repo to my docker account, and hopping the image became ready with no need of dev/debug. 

If some one can tell me if there is maintainers available tell me, otherwise i deploy a docker image base on the fix.

**Comment by avt00** [comment]
@ngosang сould you please take a look at the pull request and merge it if possible?

**Comment by CyberPoison** [comment]
Thre is a docker image for testing purposes: `rix1337/docker-flaresolverr:pull-request-715`
But with me i still with error 500. Don't understand why 🤔

**Comment by avt00** [comment]
> Thre is a docker image for testing purposes: `rix1337/docker-flaresolverr:pull-request-715` But with me i still with error 500. Don't understand why 🤔

Maybe you are still running the old version? For me this PR solved the issue.

**Comment by CyberPoison** [comment]
I have checked it double times, but image is correct. 
<img width="1034" alt="CleanShot 2023-03-05 at 18 20 02@2x" src="https://user-images.githubusercontent.com/60718477/222975703-d6b5b45a-010b-4dda-9b2c-1c8b1f0d008d.png">

**Comment by rix1337** [comment]
My docker build of #715 does not bypass Captchas. That's probably the reason why this does not work for your 

Maybe your previously failed attempts also raised the threat score for your IP

**Comment by ilike2burnthing** [comment]
This project is still maintained.

As stated in https://github.com/FlareSolverr/FlareSolverr/pull/715, headless mode isn't working on Windows. Once @furdarius resolves that, it can be merged.

**Comment by CyberPoison** [comment]
> My docker build of #715 does not bypass Captchas. That's probably the reason why this does not work for your
> 
> Maybe your previously failed attempts also raised the threat score for your IP

Yeah maybe you are correct. 
Perhaps i have tested with building a Ubuntu docker vnc, and trying access the website over a container with VNC UI, and it works.
<img width="1280" alt="CleanShot 2023-03-06 at 09 58 14@2x" src="https://user-images.githubusercontent.com/60718477/223064143-e07eef0f-ca06-4bdd-9034-71f792d9352c.png">

**Comment by ilike2burnthing** [comment]
v3.0.3 should resolve the issue. Retry a few times if it continues after updating.

**Comment by simian91** [comment]
Hello all, for me this issue still remains with v3.0.4 (using same URL as OP: https://dontorrent.ninja/ultimos). Same setup as OP, docker on debian, not using a VPN, etc.

I'm presented with the following error in the log:

`  | FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
-- | --`

Is there anything else I can try? Thanks a lot!

**Comment by ilike2burnthing** [comment]
That's a different issue. Try disabling IPv6 for FlareSolverr and Jackett/Prowlarr.

**Comment by adocampo** [comment]
It still fails here: 
```
jackett       | 03-16 08:51:37 Error Jackett.Common.IndexerException: Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       |  Jackett.Common.IndexerException: Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       | 
jackett       |  ---> Jackett.Common.ExceptionWithConfigData: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       | 
jackett       |    at Jackett.Common.Indexers.DonTorrent.PerformQueryNewest(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/DonTorrent.cs:line 183
jackett       |    at Jackett.Common.Indexers.DonTorrent.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/DonTorrent.cs:line 142
jackett       |    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 311
jackett       |    --- End of inner exception stack trace ---
jackett       |    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 329
jackett       |    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 699
jackett       |    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
jackett       |    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett       |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett       |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett       |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
jackett       | 03-16 08:51:37 Error Jackett.Common.IndexerException: Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       |  Jackett.Common.IndexerException: Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       | 
jackett       |  ---> Jackett.Common.ExceptionWithConfigData: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
jackett       | <html><head>
jackett       | <title>301 Moved Permanently</title>
jackett       | </head><body>
jackett       | <h1>Moved Permanently</h1>
jackett       | <p>The document has moved <a href="https://dontorrent.africa/ultimos">here</a>.</p>
jackett       | </body></html>
jackett       | 
jackett       |    at Jackett.Common.Indexers.DonTorrent.PerformQueryNewest(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/DonTorrent.cs:line 183
jackett       |    at Jackett.Common.Indexers.DonTorrent.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/DonTorrent.cs:line 142
jackett       |    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 311
jackett       |    --- End of inner exception stack trace ---
jackett       |    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 329
jackett       |    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 699
jackett       |    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
jackett       |    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett       |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|1
```

I've noticed, but, stariting jackett without flaresolverr returns the very  same error...

**Comment by naxeras** [comment]
I have the same problem here:

2023-03-28 19:43:27 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://dontorrent.pictures/ultimos'}
2023-03-28 19:43:31 INFO     Challenge detected. Title found: Just a moment...
2023-03-28 19:44:24 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-03-28 19:44:24 INFO     Response in 56.983 s
2023-03-28 19:44:24 INFO     172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error

Jacker is the last version.

**Comment by ilike2burnthing** [comment]
Change the domain from `pictures` to `ms` or wait for the next Jackett release in ~5hrs.

**Comment by naxeras** [comment]
Yes its working now.

Thank you very much.

Regards

**Comment by bombz88** [comment]
> Change the domain from `pictures` to `ms` or wait for the next Jackett release in ~5hrs.

Same concern, flare cannot solve challenges anymore

```
[Jackett](https://github.com/Jackett/Jackett) Version v0.22.315

2024-07-11 06:27:07 INFO     Challenge detected. Title found: Just a moment...
2024-07-11 06:28:03 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-11 06:28:03 INFO     Response in 58.231 s
2024-07-11 06:28:03 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```
