### ISSUE TITLE
BadassTorrents not working - error 500

### ISSUE THREAD

**Issue by sysqo82** [FlareSolverr/FlareSolverr#720]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.2
- Last working FlareSolverr version: none
- Operating system: windows 10 22H2
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

1. configure jackett to use flaresolverr
2. configure radarr to use badasstorrents.com to use jackett
3. search for a film

### Logged Error Messages

log file from docker desktop:
```
2023-03-05 10:06:29 2023-03-05 10:06:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://badasstorrents.com/torrents/search/Turning Red 2022/date/desc'}
2023-03-05 10:07:16 2023-03-05 10:07:16 INFO     Challenge detected. Title found: Just a moment...
2023-03-05 10:07:47 2023-03-05 10:07:47 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-03-05 10:07:47 2023-03-05 10:07:47 INFO     Response in 77.575 s
2023-03-05 10:07:47 2023-03-05 10:07:47 INFO     172.17.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

log file from jackett:
```
Jackett.Common.IndexerException: Exception (badasstorrents): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```
log file from radarr:
```
2023-03-05 10:24:13.9|Warn|HttpClient|HTTP Error - Res: [GET] http://127.0.0.1:9117/api/v2.0/indexers/badasstorrents/results/torznab/api?t=search&cat=2000&extended=1&apikey=(removed)&offset=0&limit=100&q=Dont%20Worry%20Darling%202022: 400.BadRequest (8488 bytes)
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="Jackett.Common.IndexerException: Exception (badasstorrents): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.&#xD;&#xA; ---&gt; System.TimeoutException: The operation was canceled.&#xD;&#xA; ---&gt; System.Threading.Tasks.TaskCanceledException: The operation was canceled.&#xD;&#xA; ---&gt; System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..&#xD;&#xA; ---&gt; System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 token)&#xD;&#xA;   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)&#xD;&#xA;   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)&#xD;&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xD;&#xA;   at FlareSolverrSharp.Solvers.FlareSolverr.&lt;&gt;c__DisplayClass10_0.&lt;&lt;SendFlareSolverrRequest&gt;b__0&gt;d.MoveNext()&#xD;&#xA; ---&gt; FlareSolverrSharp.Exceptions.FlareSolverrException: Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.&#xD;&#xA; ---&gt; System.TimeoutException: The operation was canceled.&#xD;&#xA; ---&gt; System.Threading.Tasks.TaskCanceledException: The operation was canceled.&#xD;&#xA; ---&gt; System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..&#xD;&#xA; ---&gt; System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 token)&#xD;&#xA;   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)&#xD;&#xA;   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)&#xD;&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xD;&#xA;   at FlareSolverrSharp.Solvers.FlareSolverr.&lt;&gt;c__DisplayClass10_0.&lt;&lt;SendFlareSolverrRequest&gt;b__0&gt;d.MoveNext()&#xD;&#xA;   at FlareSolverrSharp.Solvers.FlareSolverr.&lt;&gt;c__DisplayClass10_0.&lt;&lt;SendFlareSolverrRequest&gt;b__0&gt;d.MoveNext()&#xD;&#xA;--- End of stack trace from previous location ---&#xD;&#xA;   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)&#xD;&#xA;   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)&#xD;&#xA;   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)&#xD;&#xA;   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)&#xD;&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xD;&#xA;   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 179&#xD;&#xA;   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 219&#xD;&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 533&#xD;&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1423&#xD;&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 331&#xD;&#xA;   --- End of inner exception stack trace ---&#xD;&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 331&#xD;&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 702&#xD;&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 457" />
```

### Screenshots

![image](https://user-images.githubusercontent.com/20111075/222954389-d85ec841-e69c-4ef3-ad72-da85435a93b4.png)

**Comment by rix1337** [comment]
Fixed in #715

**Comment by sysqo82** [comment]
> Fixed in #715

thx

**Comment by sysqo82** [comment]
guess what didn't fix it?
![image](https://user-images.githubusercontent.com/20111075/222987459-fef1d40e-4d0d-4f86-9cf4-804ec430d01a.png)

**Comment by ilike2burnthing** [comment]
v3.0.3 should resolve the issue. Retry a few times if it continues after updating.

**Comment by sysqo82** [comment]
thank you, how many times is a "few times" before we can declare it's not working?
![image](https://user-images.githubusercontent.com/20111075/223144461-4808db4a-d48d-4c71-b969-9484e7fd4bb8.png)

**Comment by rix1337** [comment]
Switch IPs, then try again. You failed attempts probably raised the Threat Score for your address.

**Comment by assaf-itzikson** [comment]
ok, IP switched, testing

**Comment by sysqo82** [comment]
nope! not working

**Comment by pedipaco** [comment]
Same problem for me

**Comment by sysqo82** [comment]
@ilike2burnthing why are you closing up tickets before making sure the problem is resolved?
This is obviously, not fixed.

**Comment by ilike2burnthing** [comment]
v3.0.4

**Comment by sysqo82** [comment]
> v3.0.4

thank you, finally it's working but I had to extend the timeout to 75 seconds because it's way too slow. when it was on 55 seconds, the response got back after 59 seconds and I still got an error on radarr that the indexer failed.
![image](https://user-images.githubusercontent.com/20111075/223696318-0773362c-56e8-4f2a-8219-f6e9fbdaaf38.png)
