### ISSUE TITLE
[anidex] (configuring) Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by varosengineer** [FlareSolverr/FlareSolverr#782]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.1.2
- Last working FlareSolverr version: -
- Operating system: Linux AS3302T 4.9.119 aarch64
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):

#13 0x0055740efdec <unknown>
#14 0x00557412bd94 <unknown>
#15 0x00557412bf54 <unknown>
#16 0x005574144760 <unknown>
#17 0x007f9fb6a648 start_thread
#18 0x007f9f315c1c <unknown>
2023-05-23 15:21:26 INFO     FlareSolverr 3.1.2
2023-05-23 15:21:26 INFO     Testing web browser installation...
2023-05-23 15:21:26 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-05-23 15:21:26 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-05-23 15:21:28 INFO     Chrome / Chromium major version: 111
2023-05-23 15:21:28 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 194, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 447, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 710, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60001
from chrome not reachable
Stacktrace:
#0 0x00556c587890 <unknown>
#1 0x00556c367600 <unknown>
#2 0x00556c358fc8 <unknown>
#3 0x00556c38f09c <unknown>
#4 0x00556c388d3c <unknown>
#5 0x00556c3ca5b8 <unknown>
#6 0x00556c3924a4 <unknown>
#7 0x00556c393730 <unknown>
#8 0x00556c5ceb4c <unknown>
#9 0x00556c5d1324 <unknown>
#10 0x00556c5d0e48 <unknown>
#11 0x00556c5bd1fc <unknown>
#12 0x00556c5d1c74 <unknown>
#13 0x00556c5afdec <unknown>
#14 0x00556c5ebd94 <unknown>
#15 0x00556c5ebf54 <unknown>
#16 0x00556c604760 <unknown>
#17 0x007f9e9c0648 start_thread
#18 0x007f9e16bc1c <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 198, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:60001
from chrome not reachable
Stacktrace:
#0 0x00556c587890 <unknown>
#1 0x00556c367600 <unknown>
#2 0x00556c358fc8 <unknown>
#3 0x00556c38f09c <unknown>
#4 0x00556c388d3c <unknown>
#5 0x00556c3ca5b8 <unknown>
#6 0x00556c3924a4 <unknown>
#7 0x00556c393730 <unknown>
#8 0x00556c5ceb4c <unknown>
#9 0x00556c5d1324 <unknown>
#10 0x00556c5d0e48 <unknown>
#11 0x00556c5bd1fc <unknown>
#12 0x00556c5d1c74 <unknown>
#13 0x00556c5afdec <unknown>
#14 0x00556c5ebd94 <unknown>
#15 0x00556c5ebf54 <unknown>
#16 0x00556c604760 <unknown>
#17 0x007f9e9c0648 start_thread
#18 0x007f9e16bc1c <unknown>
2023-05-23 15:22:37 INFO     FlareSolverr 3.1.2
2023-05-23 15:22:37 INFO     Testing web browser installation...
2023-05-23 15:22:37 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-05-23 15:22:37 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-05-23 15:22:37 INFO     Chrome / Chromium major version: 111
2023-05-23 15:22:37 INFO     Launching web browser...
```
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```


### Description

To reproduce I just had to install flaresolverr in docker on my Asustor AS3302T and check the logs.

### Logged Error Messages

```text
#13 0x0055740efdec <unknown>
#14 0x00557412bd94 <unknown>
#15 0x00557412bf54 <unknown>
#16 0x005574144760 <unknown>
#17 0x007f9fb6a648 start_thread
#18 0x007f9f315c1c <unknown>
2023-05-23 15:21:26 INFO     FlareSolverr 3.1.2
2023-05-23 15:21:26 INFO     Testing web browser installation...
2023-05-23 15:21:26 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-05-23 15:21:26 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-05-23 15:21:28 INFO     Chrome / Chromium major version: 111
2023-05-23 15:21:28 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 194, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 447, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 710, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60001
from chrome not reachable
Stacktrace:
#0 0x00556c587890 <unknown>
#1 0x00556c367600 <unknown>
#2 0x00556c358fc8 <unknown>
#3 0x00556c38f09c <unknown>
#4 0x00556c388d3c <unknown>
#5 0x00556c3ca5b8 <unknown>
#6 0x00556c3924a4 <unknown>
#7 0x00556c393730 <unknown>
#8 0x00556c5ceb4c <unknown>
#9 0x00556c5d1324 <unknown>
#10 0x00556c5d0e48 <unknown>
#11 0x00556c5bd1fc <unknown>
#12 0x00556c5d1c74 <unknown>
#13 0x00556c5afdec <unknown>
#14 0x00556c5ebd94 <unknown>
#15 0x00556c5ebf54 <unknown>
#16 0x00556c604760 <unknown>
#17 0x007f9e9c0648 start_thread
#18 0x007f9e16bc1c <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 198, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:60001
from chrome not reachable
Stacktrace:
#0 0x00556c587890 <unknown>
#1 0x00556c367600 <unknown>
#2 0x00556c358fc8 <unknown>
#3 0x00556c38f09c <unknown>
#4 0x00556c388d3c <unknown>
#5 0x00556c3ca5b8 <unknown>
#6 0x00556c3924a4 <unknown>
#7 0x00556c393730 <unknown>
#8 0x00556c5ceb4c <unknown>
#9 0x00556c5d1324 <unknown>
#10 0x00556c5d0e48 <unknown>
#11 0x00556c5bd1fc <unknown>
#12 0x00556c5d1c74 <unknown>
#13 0x00556c5afdec <unknown>
#14 0x00556c5ebd94 <unknown>
#15 0x00556c5ebf54 <unknown>
#16 0x00556c604760 <unknown>
#17 0x007f9e9c0648 start_thread
#18 0x007f9e16bc1c <unknown>
2023-05-23 15:22:37 INFO     FlareSolverr 3.1.2
2023-05-23 15:22:37 INFO     Testing web browser installation...
2023-05-23 15:22:37 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-05-23 15:22:37 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-05-23 15:22:37 INFO     Chrome / Chromium major version: 111
2023-05-23 15:22:37 INFO     Launching web browser...
```

**Comment by ngosang** [comment]
This is happening only in ASUSTOR #687 #688
It could be some bug in Chomium, some missing dependency outdated Docker or Linux kernel....

You could try to run those commands in the ASUSTOR shell and post back the output:
```
docker run -it flaresolverr/flaresolverr:3.1.3 bash
xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox
```

**Comment by varosengineer** [comment]
> This is happening only in ASUSTOR #687 #688 It could be some bug in Chomium, some missing dependency outdated Docker or Linux kernel....
> 
> You could try to run those commands in the ASUSTOR shell and post back the output:
> 
> ```
> docker run -it flaresolverr/flaresolverr:3.1.3 bash
> xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox
> ```

I guess in the first command there is a typo, the version I have installed is `3.1.2`. Here are the outputs of the commands:

> docker run -it flaresolverr/flaresolverr:3.1.3 bash

```
Unable to find image 'flaresolverr/flaresolverr:3.1.2' locally
docker: Error response from daemon: manifest for flaresolverr/flaresolverr:3.1.2 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

> xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox

```
-sh: xvfb-run: not found
```

Thanks in advance.

**Comment by ngosang** [comment]
Sorry, I put the commands wrong. Try these:
```
docker run -it flaresolverr/flaresolverr:v3.2.0 bash
xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox
```

**Comment by varosengineer** [comment]
> Sorry, I put the commands wrong. Try these:
> 
> ```
> docker run -it flaresolverr/flaresolverr:v3.2.0 bash
> xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox
> ```

```
[20:46:0525/101625.013577:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:50:0525/101630.221296:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:50:0525/101630.221492:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:46:0525/101630.408032:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[20:46:0525/101630.408170:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[20:20:0525/101630.820491:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[56:56:0525/101631.059473:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[20:46:0525/101631.363554:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[20:46:0525/101631.363667:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[56:56:0525/101631.371104:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[56:56:0525/101631.371419:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[56:56:0525/101631.372008:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[56:56:0525/101631.372257:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[56:56:0525/101631.372416:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[56:56:0525/101631.372572:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[56:56:0525/101631.373004:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[56:56:0525/101631.373986:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[56:56:0525/101631.374334:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[56:56:0525/101631.374493:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[56:56:0525/101631.374911:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[56:56:0525/101631.375078:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[56:56:0525/101631.375205:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[56:56:0525/101631.375333:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[56:56:0525/101631.375460:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[56:56:0525/101631.410535:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[20:89:0525/101632.718077:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:89:0525/101632.718377:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:89:0525/101632.718637:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:89:0525/101632.718760:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[20:89:0525/101632.718874:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[88:88:0525/101632.888464:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[88:88:0525/101632.888861:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[88:88:0525/101632.889368:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[88:88:0525/101632.889977:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[88:88:0525/101632.890204:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[88:88:0525/101632.890332:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[88:88:0525/101632.890472:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[88:88:0525/101632.890616:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[88:88:0525/101632.891748:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[88:88:0525/101632.891976:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[88:88:0525/101632.892142:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[88:88:0525/101632.892527:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[88:88:0525/101632.892689:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[88:88:0525/101632.892807:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[88:88:0525/101632.893020:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[88:88:0525/101632.893201:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[88:88:0525/101632.900549:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

**Comment by ngosang** [comment]
@varosengineer I think I can fix the issue. Just test the last commands and post the traces. I will release the fixed version if it works.

```
docker run -it flaresolverr/flaresolverr:v3.2.0 bash
xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox --use-gl=swiftshader
```

**Comment by varosengineer** [comment]
> xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox --use-gl=swiftshader

```
[21:48:0529/114112.896666:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:51:0529/114115.304072:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:51:0529/114115.304300:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:48:0529/114115.364397:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:48:0529/114115.364515:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[57:57:0529/114115.586848:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[57:57:0529/114115.669330:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[21:21:0529/114115.683091:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[21:48:0529/114115.769026:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:48:0529/114115.769934:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:91:0529/114116.604735:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:91:0529/114116.604909:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:91:0529/114116.605119:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:91:0529/114116.605288:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:91:0529/114116.605917:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[90:90:0529/114116.614761:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[90:90:0529/114116.721355:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

**Comment by PrivatePengu** [comment]
First time setting up, am getting same error on Synology NAS with 64bit Intel chip, running above commands yielded the same results for me:


```
[19:47:0601/214633.985385:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:50:0601/214717.050556:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:50:0601/214717.797517:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:47:0601/214727.517362:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[19:47:0601/214727.558046:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[19:19:0601/214735.946970:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[59:59:0601/214756.802491:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[59:59:0601/214756.861363:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[59:59:0601/214756.861433:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[59:59:0601/214756.917857:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[59:59:0601/214756.917950:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[59:59:0601/214756.917991:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[59:59:0601/214756.918030:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[59:59:0601/214756.918076:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[59:59:0601/214756.918313:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[59:59:0601/214756.918395:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[59:59:0601/214756.918448:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[59:59:0601/214756.918529:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[59:59:0601/214756.918576:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[59:59:0601/214756.918617:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[59:59:0601/214756.918654:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[59:59:0601/214756.918691:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[59:59:0601/214823.287082:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[19:47:0601/214908.768215:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[19:47:0601/214909.148775:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[19:85:0601/214920.688529:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:85:0601/214920.688604:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:85:0601/214920.688661:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:85:0601/214920.688695:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:85:0601/214920.688727:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[84:84:0601/214929.598836:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[84:84:0601/214929.599092:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[84:84:0601/214929.599135:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[84:84:0601/214929.599323:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[84:84:0601/214929.599397:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[84:84:0601/214929.599450:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[84:84:0601/214929.599530:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[84:84:0601/214929.673382:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[84:84:0601/214929.674352:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[84:84:0601/214929.676360:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[84:84:0601/214929.676544:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[84:84:0601/214929.677428:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
[84:84:0601/214929.677499:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[84:84:0601/214929.677545:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[84:84:0601/214929.677615:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
[84:84:0601/214929.677684:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[84:84:0601/214930.590231:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

Then, with ``--use-gl=swiftshader``:

```
[135:161:0601/215745.849388:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:166:0601/215746.565708:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:166:0601/215746.565769:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:161:0601/215746.609736:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[135:161:0601/215746.609774:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[172:172:0601/215746.651363:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[135:135:0601/215746.695670:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[172:172:0601/215746.729234:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[135:161:0601/215746.880058:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[135:161:0601/215746.880097:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[135:161:0601/215748.086091:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[135:161:0601/215748.086195:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[217:217:0601/215748.959362:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[217:217:0601/215749.083452:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[135:225:0601/215749.120688:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:225:0601/215749.120737:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:225:0601/215749.120794:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:225:0601/215749.120830:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[135:225:0601/215749.120864:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[226:226:0601/215749.145524:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[226:226:0601/215749.181057:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[135:162:0601/215753.389503:ERROR:udev_watcher.cc(98)] Failed to begin udev enumeration.
```

**Comment by Bishop-trevorstuart** [comment]
I too seem to be getting this issue. I updated to the latest docker inage, but still not able to use flaresolverr. 

sudo docker run -it flaresolverr/flaresolverr:v3.2.0 bash
Unable to find image 'flaresolverr/flaresolverr:v3.2.0' locally
v3.2.0: Pulling from flaresolverr/flaresolverr
Digest: sha256:9975b310d0943b7ff0c2b92b52a00f7fa5c0584f67575b7e00018dccbbb6a61e
Status: Downloaded newer image for flaresolverr/flaresolverr:v3.2.0
flaresolverr@253ef2070cc4:~$ sudo xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox --use-gl=swiftshader
bash: sudo: command not found
flaresolverr@253ef2070cc4:~$ sudo docker run -it flaresolverr/flaresolverr:v3.2.0 bash
xvfb-run -s "-screen 0 1600x1200x24" chromium --no-sandbox --use-gl=swiftshader
bash: sudo: command not found
[21:48:0602/223144.812470:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:52:0602/223145.211014:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:52:0602/223145.212027:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:48:0602/223145.244629:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:48:0602/223145.244750:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[61:61:0602/223145.275758:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[21:21:0602/223145.286257:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[61:61:0602/223145.309277:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[21:48:0602/223145.325819:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:48:0602/223145.326134:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[77:77:0602/223145.492540:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[21:86:0602/223145.510973:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:86:0602/223145.515267:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:86:0602/223145.516938:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:86:0602/223145.518007:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:86:0602/223145.519260:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[77:77:0602/223145.531815:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[21:48:0602/223145.696434:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[21:48:0602/223145.696846:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
^C[87:87:0602/223202.757713:ERROR:connection.cc(46)] X connection error received.
[87:101:0602/223202.765492:ERROR:connection.cc(46)] X connection error received.

**Comment by ngosang** [comment]
I think it's fixed in => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.1

**Comment by varosengineer** [comment]
> I think it's fixed in => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.1

I tried it this morning and for me it still doesn't work. One detail, I had to specify the version in the docker-compose, the "latest" tag was pulling version 3.2.0.

```
2023-06-12 08:07:51 INFO     FlareSolverr 3.2.1
2023-06-12 08:07:51 INFO     Testing web browser installation...
2023-06-12 08:07:51 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-06-12 08:07:51 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-06-12 08:08:04 INFO     Chrome / Chromium major version: 114
2023-06-12 08:08:04 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 207, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 93, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 447, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 710, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:58685
from chrome not reachable
Stacktrace:
#0 0x005585c36ab0 <unknown>
#1 0x005585991d98 <unknown>
#2 0x00558598335c <unknown>
#3 0x0055859b97cc <unknown>
#4 0x0055859b3530 <unknown>
#5 0x0055859f2c58 <unknown>
#6 0x0055859bcc44 <unknown>
#7 0x0055859bded0 <unknown>
#8 0x005585c037a8 <unknown>
#9 0x005585c06fe0 <unknown>
#10 0x005585c06b7c <unknown>
#11 0x005585c0dbc8 <unknown>
#12 0x005585c076e8 <unknown>
#13 0x005585be0264 <unknown>
#14 0x005585c20eac <unknown>
#15 0x005585c21074 <unknown>
#16 0x005585c2f2cc <unknown>
#17 0x007f8f439648 start_thread
#18 0x007f8ebe4fdc <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 211, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:58685
from chrome not reachable
Stacktrace:
#0 0x005585c36ab0 <unknown>
#1 0x005585991d98 <unknown>
#2 0x00558598335c <unknown>
#3 0x0055859b97cc <unknown>
#4 0x0055859b3530 <unknown>
#5 0x0055859f2c58 <unknown>
#6 0x0055859bcc44 <unknown>
#7 0x0055859bded0 <unknown>
#8 0x005585c037a8 <unknown>
#9 0x005585c06fe0 <unknown>
#10 0x005585c06b7c <unknown>
#11 0x005585c0dbc8 <unknown>
#12 0x005585c076e8 <unknown>
#13 0x005585be0264 <unknown>
#14 0x005585c20eac <unknown>
#15 0x005585c21074 <unknown>
#16 0x005585c2f2cc <unknown>
#17 0x007f8f439648 start_thread
#18 0x007f8ebe4fdc <unknown>
```

**Comment by PrivatePengu** [comment]
> First time setting up, am getting same error on Synology NAS with 64bit Intel chip, running above commands yielded the same results for me:
> 
> ```
> [19:47:0601/214633.985385:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:50:0601/214717.050556:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:50:0601/214717.797517:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:47:0601/214727.517362:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [19:47:0601/214727.558046:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [19:19:0601/214735.946970:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
> [59:59:0601/214756.802491:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [59:59:0601/214756.861363:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [59:59:0601/214756.861433:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
> [59:59:0601/214756.917857:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [59:59:0601/214756.917950:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [59:59:0601/214756.917991:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
> [59:59:0601/214756.918030:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
> [59:59:0601/214756.918076:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
> [59:59:0601/214756.918313:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [59:59:0601/214756.918395:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [59:59:0601/214756.918448:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
> [59:59:0601/214756.918529:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [59:59:0601/214756.918576:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [59:59:0601/214756.918617:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
> [59:59:0601/214756.918654:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
> [59:59:0601/214756.918691:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
> [59:59:0601/214823.287082:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
> [19:47:0601/214908.768215:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [19:47:0601/214909.148775:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [19:85:0601/214920.688529:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:85:0601/214920.688604:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:85:0601/214920.688661:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:85:0601/214920.688695:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [19:85:0601/214920.688727:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [84:84:0601/214929.598836:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [84:84:0601/214929.599092:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [84:84:0601/214929.599135:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
> [84:84:0601/214929.599323:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [84:84:0601/214929.599397:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [84:84:0601/214929.599450:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
> [84:84:0601/214929.599530:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
> [84:84:0601/214929.673382:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
> [84:84:0601/214929.674352:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [84:84:0601/214929.676360:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [84:84:0601/214929.676544:ERROR:gl_display.cc(771)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
> [84:84:0601/214929.677428:ERROR:angle_platform_impl.cc(43)] Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
> [84:84:0601/214929.677499:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: GLX is not present.
> [84:84:0601/214929.677545:ERROR:gl_display.cc(771)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
> [84:84:0601/214929.677615:ERROR:gl_display.cc(805)] Initialization of all EGL display types failed.
> [84:84:0601/214929.677684:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
> [84:84:0601/214930.590231:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
> ```
> 
> Then, with `--use-gl=swiftshader`:
> 
> ```
> [135:161:0601/215745.849388:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:166:0601/215746.565708:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:166:0601/215746.565769:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:161:0601/215746.609736:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [135:161:0601/215746.609774:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [172:172:0601/215746.651363:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
> [135:135:0601/215746.695670:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
> [172:172:0601/215746.729234:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
> [135:161:0601/215746.880058:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [135:161:0601/215746.880097:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [135:161:0601/215748.086091:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [135:161:0601/215748.086195:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [217:217:0601/215748.959362:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
> [217:217:0601/215749.083452:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
> [135:225:0601/215749.120688:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:225:0601/215749.120737:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:225:0601/215749.120794:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:225:0601/215749.120830:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [135:225:0601/215749.120864:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [226:226:0601/215749.145524:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
> [226:226:0601/215749.181057:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
> [135:162:0601/215753.389503:ERROR:udev_watcher.cc(98)] Failed to begin udev enumeration.
> ```

Will mention that either the new version (from 3.2.0 to 3.2.1), updating to the DSM 7.2 beta, or upgrading from 2 gb to 18 gb system memory has fixed the issue for me and flaresolverr is working on my system

**Comment by hastalamuerte** [comment]
Exception ignored in: <function Chrome.__del__ at 0x00000196AF8296C0>
Traceback (most recent call last):
  File "undetected_chromedriver\__init__.py", line 804, in __del__
  File "undetected_chromedriver\__init__.py", line 759, in quit
OSError: [WinError 6] The handle is invalid

win binaries

**Comment by gingerbeardman** [comment]
same problem here since a recent update

**Comment by Redirts** [comment]
Tried with 3.3.0 and I get the same errors as above.

1. Running on docker on Pi 3B

2. When a request comes in I get "Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:40313"

3. If I try the commands above by interactive shell and then xvfb-run command I get the same output as above: 
[21:48:0802/201239.345545:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1
