### ISSUE TITLE
pt.btschool.club Error solving the challenge

### ISSUE THREAD

**Issue by today2004** [FlareSolverr/FlareSolverr#828]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:https://pt.btschool.club/
```

### Description

https://pt.btschool.club The website has detected it, but it is automatic and does not require manual buttons, resulting in a click_ Verify failed and exited due to timeout. What should I do about this。

### Logged Error Messages

```text
2023-07-23 01:55:25 INFO     ReqId 139986346858240 Response in 61.202 s
2023-07-23 01:55:25 INFO     ReqId 139986346858240 172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
2023-07-23 01:55:32 INFO     ReqId 139986338465536 Incoming request => POST /v1 body: {'cmd': 'request.get', 'maxTimeout': 60000, 'url': 'https://pt.btschool.club/'}
2023-07-23 01:55:32 DEBUG    ReqId 139986338465536 Launching web browser...
2023-07-23 01:55:32 DEBUG    ReqId 139986338465536 Started executable: `/app/chromedriver` in a child process with pid: 493
2023-07-23 01:55:33 DEBUG    ReqId 139986338465536 New instance of webdriver has been created to perform the request
2023-07-23 01:55:33 DEBUG    ReqId 139986303846144 Navigating to... https://pt.btschool.club/
2023-07-23 01:55:36 INFO     ReqId 139986303846144 Challenge detected. Title found: Just a moment...
2023-07-23 01:55:36 DEBUG    ReqId 139986303846144 Waiting for title (attempt 1): Just a moment...
2023-07-23 01:55:55 DEBUG    ReqId 139986303846144 Timeout waiting for selector
2023-07-23 01:55:55 DEBUG    ReqId 139986303846144 Try to find the Cloudflare verify checkbox
2023-07-23 01:55:56 DEBUG    ReqId 139986303846144 Cloudflare verify checkbox not found on the page
2023-07-23 01:55:56 DEBUG    ReqId 139986303846144 Try to find the Cloudflare 'Verify you are human' button
2023-07-23 01:55:56 DEBUG    ReqId 139986303846144 The Cloudflare 'Verify you are human' button not found on the page
2023-07-23 01:55:58 DEBUG    ReqId 139986303846144 Waiting for title (attempt 2): Just a moment...
2023-07-23 01:56:16 DEBUG    ReqId 139986303846144 Timeout waiting for selector
2023-07-23 01:56:16 DEBUG    ReqId 139986303846144 Try to find the Cloudflare verify checkbox
2023-07-23 01:56:16 DEBUG    ReqId 139986303846144 Cloudflare verify checkbox not found on the page
2023-07-23 01:56:16 DEBUG    ReqId 139986303846144 Try to find the Cloudflare 'Verify you are human' button
2023-07-23 01:56:16 DEBUG    ReqId 139986303846144 The Cloudflare 'Verify you are human' button not found on the page
2023-07-23 01:56:18 DEBUG    ReqId 139986303846144 Waiting for title (attempt 3): Just a moment...
2023-07-23 01:56:33 DEBUG    ReqId 139986338465536 A used instance of webdriver has been destroyed
2023-07-23 01:56:33 ERROR    ReqId 139986338465536 Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-07-23 01:56:33 DEBUG    ReqId 139986338465536 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 60.0 seconds.', 'startTimestamp': 1690077332354, 'endTimestamp': 1690077393678, 'version': '3.2.2'}
2023-07-23 01:56:33 INFO     ReqId 139986338465536 Response in 61.324 s
2023-07-23 01:56:33 INFO     ReqId 139986338465536 172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by ipaqi** [comment]
Similar thing happening to me with ff.net via FanFicFare plugin for Calibre:

including log with LOG_LEVEL=debug and LOG_HTML=true

[log.txt](https://github.com/FlareSolverr/FlareSolverr/files/12139133/log.txt)

**Comment by dxgs2154** [comment]
I'm also facing the this problem on linux server. do you have any solution to solved it?

2023-07-24 04:15:03 INFO     FlareSolverr 3.2.2
2023-07-24 04:15:03 INFO     Testing web browser installation...
2023-07-24 04:15:03 INFO     Platform: Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.31
2023-07-24 04:15:03 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-07-24 04:15:03 INFO     Chrome / Chromium major version: 114
2023-07-24 04:15:03 INFO     Launching web browser...
2023-07-24 04:15:04 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
2023-07-24 04:15:04 INFO     Test successful!
2023-07-24 04:15:04 INFO     Serving on http://0.0.0.0:8191
2023-07-24 04:15:25 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://18comic.vip/photo/284095', 'maxTimeout': 120000}
2023-07-24 04:15:26 INFO     Challenge detected. Title found: Just a moment...

**Comment by ivanjx** [comment]
here is my case (the log order is from bottom to top)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/12814796/ac5cadb4-6883-4378-be43-41e5d14811ba)

**Comment by xja** [comment]
My log with LOG_LEVEL=debug and LOG_HTML=true on pt.btshool.club
[pt.btschool.club.log](https://github.com/FlareSolverr/FlareSolverr/files/12142911/pt.btschool.club.log)

**Comment by today2004** [comment]
Well, that's it. Can't jump through it all the time. It's on page “Just a moment...”, and the chrome browser  normal

**Comment by mwilky** [comment]
I'm having this happen to me on all sites also now :(

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811

**Comment by Anatharias** [comment]
same issue with test domain torrentQQ247.com as indicated in the troubleshooting steps and yggtorrent.wtf as well
`2023-07-29 22:56:53 DEBUG    ReqId 140466947344128 Try to find the Cloudflare 'Verify you are human' button
2023-07-29 22:56:53 DEBUG    ReqId 140466947344128 The Cloudflare 'Verify you are human' button not found on the page
2023-07-29 22:56:55 DEBUG    ReqId 140466947344128 Waiting for title (attempt 5): Just a moment...
2023-07-29 22:57:05 DEBUG    ReqId 140466947344128 Timeout waiting for selector`

**Comment by ThomasF34** [comment]
I am having the same issue. Is there any work around so far?

**Comment by Draky50110** [comment]
Not now.

**Comment by Tsuna77** [comment]
same issue with yggtorent.wtf :-(

**Comment by digitalnomad91** [comment]
Working solution & another workaround for when undetect\_chromedriver & flaresolverr aren't working if/when cloudflare is winning again in this war of attrition:

https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1660158095

**Comment by today2004** [comment]
> 如果/当cloudflare在这场消耗战中再次获胜时，当undetect_chromedriver和flaresolverr不起作用时的工作解决方案和另一种解决方法：
> 
> [第811章（评论）](https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1660158095)

Thank you for your hard work. Let me take a look

**Comment by today2004** [comment]
> Working solution & another workaround for when undetect_chromedriver & flaresolverr aren't working if/when cloudflare is winning again in this war of attrition:
> 
> [#811 (comment)](https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1660158095)

Thank you for your hard work. Let me take a look

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0

**Comment by SnowTechnical** [comment]
Hello everyone,
Despite the new version I still have the "Error solving the challenge" problem, I don't understand why.
I am on docker on my synology with this command:
```
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.0
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1026
      - PGID=100
      - TZ=Europe/London
      - LOG_FILE=/volume1/docker/Flaresolverr/log/flaresolverr.log
    ports:
      - 8191:8191
```

**Comment by Catif** [comment]
> Hello everyone, Despite the new version I still have the "Error solving the challenge" problem, I don't understand why. I am on docker on my synology with this command:
> 
> ```
> version: "2.1"
> services:
>   flaresolverr:
>     # DockerHub mirror flaresolverr/flaresolverr:latest
>     image: ghcr.io/flaresolverr/flaresolverr:v3.3.2
>     container_name: flaresolverr
>     environment:
>       - LOG_LEVEL=${LOG_LEVEL:-debug}
>       - LOG_HTML=${LOG_HTML:-false}
>       - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
>       - PUID=1026
>       - PGID=100
>       - TZ=Europe/London
>     ports:
>       - "${PORT:-8191}:8191"
> ```

I don't specify PUID and PGID and that works for me.

```yml
version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.2
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```
