### ISSUE TITLE
Timeout waiting for selector

### ISSUE THREAD

**Issue by whatusername000** [FlareSolverr/FlareSolverr#885]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.4
- Last working FlareSolverr version: 3.3.4
- Operating system: linux
- Are you using Docker: [yes/no] y
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] n
- Are you using a Proxy: [yes/no] n
- Are you using Captcha Solver: [yes/no] n
- If using captcha solver, which one:
- URL to test this issue: https://extremereportbot.com/
```

### Description

timeout after 1s,is it too short?
```
2023-09-02 15:24:28 DEBUG    ReqId 140074962396928 Waiting for title (attempt 39): Just a moment...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-02 15:24:31 DEBUG    ReqId 140074962396928 Waiting for title (attempt 40): Just a moment...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-02 15:24:34 DEBUG    ReqId 140074962396928 Waiting for title (attempt 41): Just a moment...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
```

### Logged Error Messages

```text
2023-09-02 15:24:28 DEBUG    ReqId 140074962396928 Waiting for title (attempt 39): Just a moment...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:29 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-02 15:24:31 DEBUG    ReqId 140074962396928 Waiting for title (attempt 40): Just a moment...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:32 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-02 15:24:34 DEBUG    ReqId 140074962396928 Waiting for title (attempt 41): Just a moment...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Timeout waiting for selector
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Try to find the Cloudflare verify checkbox...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Cloudflare verify checkbox not found on the page.
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 Try to find the Cloudflare 'Verify you are human' button...
2023-09-02 15:24:35 DEBUG    ReqId 140074962396928 The Cloudflare 'Verify you are human' button not found on the page.
```

**Comment by inverimus** [comment]
I'm getting the same thing, it's always failing waiting for selector.

**Comment by Woody-Stock** [comment]
I upgraded to v3.3.4 but still have the issue from 3.3.3

**Comment by ilike2burnthing** [comment]
The default is 60s, so yes 1s too short.

Complete the environment information in full.

**Comment by whatusername000** [comment]
> The default is 60s, so yes 1s too short.
> 
> Complete the environment information in full.

 docker v3.3.4  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

**Comment by ilike2burnthing** [comment]
> - URL to test this issue:

**Comment by whatusername000** [comment]
> > * URL to test this issue:

https://extremereportbot.com/

**Comment by ilike2burnthing** [comment]
```bash
curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url":"https://extremereportbot.com/",
  "maxTimeout": 60000
}'
```

Working fine here. What are you using?

**Comment by whatusername000** [comment]
> ```shell
> curl -L -X POST 'http://localhost:8191/v1' \
> -H 'Content-Type: application/json' \
> --data-raw '{
>   "cmd": "request.get",
>   "url":"https://extremereportbot.com/",
>   "maxTimeout": 60000
> }'
> ```
> 
> Working fine here. What are you using?

Before September 1st, using v3.3.1 is effective as my server is too far away from the target server and it will take approximately two and a half minutes to complete.I only updated the version to v3.3.4-docker yesterday.

```
function cfProxy(url) {
        let startTime=new Date().getTime()
        console.log(`${url}---${new Date()}`)
        
        return new Promise((resolve, reject) => {
            let proxyUrl = 'http://localhost:8191/v1'; 
            proxyUrl="http://flaresolver.anybot.site/v1"

            let proxyData = {
                cmd: 'request.get',
                url: url, 
                maxTimeout: 1000 * 60 * 10 
            };
            
            if(cookies){
                proxyData.cookies=cookies
                console.log("--use cookie--")
            }
            let proxyOptions = {
                url: proxyUrl,
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json' 
                },
                json: proxyData 
            };
            request(proxyOptions, (error, response, body) => {
                if (error) {
                    console.error('Error:', error);
                    reject(error)
                } else {
                    if (body.status == 'ok') {
                        let diffTime=(new Date().getTime()-startTime)/1000
                        cookies=body.solution.cookies
                        resolve(body.solution.response)
                    } else {
                        console.log(body); 
                        reject(body)
                    }
                }
            });

        })

    }
```

**Comment by ilike2burnthing** [comment]
Change maxTimeout from `1000 * 60 * 10` to just `600000`.

**Comment by whatusername000** [comment]
> Change maxTimeout from `1000 * 60 * 10` to just `600000`.

JS will automatically compute it.It shouldn't be that reason,the params received by flareSolverr is 600000

**Comment by ilike2burnthing** [comment]
If you run the simple curl command above, does that work?

**Comment by whatusername000** [comment]
> Contributor

same problem

```
2023-09-03 07:22:24 DEBUG    ReqId 139759466309376 Navigating to... https://extremereportbot.com/
2023-09-03 07:22:27 INFO     ReqId 139759466309376 Challenge detected. Title found: Just a moment...
2023-09-03 07:22:27 DEBUG    ReqId 139759466309376 Waiting for title (attempt 1): Just a moment...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Timeout waiting for selector
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Try to find the Cloudflare verify checkbox...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Cloudflare verify checkbox not found on the page.
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Try to find the Cloudflare 'Verify you are human' button...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-03 07:22:30 DEBUG    ReqId 139759466309376 Waiting for title (attempt 2): Just a moment...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Timeout waiting for selector
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Try to find the Cloudflare verify checkbox...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Cloudflare verify checkbox not found on the page.
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Try to find the Cloudflare 'Verify you are human' button...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-03 07:22:33 DEBUG    ReqId 139759466309376 Waiting for title (attempt 3): Just a moment...
```

**Comment by whatusername000** [comment]
> If you run the simple curl command above, does that work?

same problem
```
2023-09-03 07:22:24 DEBUG    ReqId 139759466309376 Navigating to... https://extremereportbot.com/
2023-09-03 07:22:27 INFO     ReqId 139759466309376 Challenge detected. Title found: Just a moment...
2023-09-03 07:22:27 DEBUG    ReqId 139759466309376 Waiting for title (attempt 1): Just a moment...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Timeout waiting for selector
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Try to find the Cloudflare verify checkbox...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Cloudflare verify checkbox not found on the page.
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 Try to find the Cloudflare 'Verify you are human' button...
2023-09-03 07:22:28 DEBUG    ReqId 139759466309376 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-03 07:22:30 DEBUG    ReqId 139759466309376 Waiting for title (attempt 2): Just a moment...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Timeout waiting for selector
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Try to find the Cloudflare verify checkbox...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Cloudflare verify checkbox not found on the page.
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 Try to find the Cloudflare 'Verify you are human' button...
2023-09-03 07:22:31 DEBUG    ReqId 139759466309376 The Cloudflare 'Verify you are human' button not found on the page.
2023-09-03 07:22:33 DEBUG    ReqId 139759466309376 Waiting for title (attempt 3): Just a moment...
```

**Comment by whatusername000** [comment]
> If you run the simple curl command above, does that work?


`Timed out receiving message from renderer: 300.000`  this timeout is 300s, which I think is the cause

it's weird,I use `info` mode,all reqeusts have failed,if I use 'debug' mode,it works now

```
{
  status: 'error',
  message: 'Error: Error solving the challenge. Message: timeout: Timed out receiving message from renderer: 300.000\\n  (Session info: chrome=116.0.5845.140)\\nStacktrace:\\n#0 0x55f98870d023 <unknown>\\n#1 0x55f9884299a8 <unknown>\\n#2 0x55f988412441 <unknown>\\n#3 0x55f988412216 <unknown>\\n#4 0x55f988410cdb <unknown>\\n#5 0x55f9884112fd <unknown>\\n#6 0x55f988425a53 <unknown>\\n#7 0x55f988426a32 <unknown>\\n#8 0x55f988433faf <unknown>\\n#9 0x55f988437f31 <unknown>\\n#10 0x55f9884118c7 <unknown>\\n#11 0x55f988433df0 <unknown>\\n#12 0x55f9884a99bb <unknown>\\n#13 0x55f988491bb3 <unknown>\\n#14 0x55f98845c9de <unknown>\\n#15 0x55f98845dd72 <unknown>\\n#16 0x55f9886dbfb6 <unknown>\\n#17 0x55f9886df02d <unknown>\\n#18 0x55f9886deac6 <unknown>\\n#19 0x55f9886df4d5 <unknown>\\n#20 0x55f9886e590b <unknown>\\n#21 0x55f9886df856 <unknown>\\n#22 0x55f9886b8b0d <unknown>\\n#23 0x55f9886f8265 <unknown>\\n#24 0x55f9886f845f <unknown>\\n#25 0x55f98870604f <unknown>\\n#26 0x7f91dba96ea7 start_thread\\n',
  startTimestamp: 1693726766325,
  endTimestamp: 1693727085985,
  version: '3.3.4'
}

```

**Comment by whatusername000** [comment]
> > If you run the simple curl command above, does that work?
> 
> `Timed out receiving message from renderer: 300.000` this timeout is 300s, which I think is the cause
> 
> ```
> {
>   status: 'error',
>   message: 'Error: Error solving the challenge. Message: timeout: Timed out receiving message from renderer: 300.000\\n  (Session info: chrome=116.0.5845.140)\\nStacktrace:\\n#0 0x55f98870d023 <unknown>\\n#1 0x55f9884299a8 <unknown>\\n#2 0x55f988412441 <unknown>\\n#3 0x55f988412216 <unknown>\\n#4 0x55f988410cdb <unknown>\\n#5 0x55f9884112fd <unknown>\\n#6 0x55f988425a53 <unknown>\\n#7 0x55f988426a32 <unknown>\\n#8 0x55f988433faf <unknown>\\n#9 0x55f988437f31 <unknown>\\n#10 0x55f9884118c7 <unknown>\\n#11 0x55f988433df0 <unknown>\\n#12 0x55f9884a99bb <unknown>\\n#13 0x55f988491bb3 <unknown>\\n#14 0x55f98845c9de <unknown>\\n#15 0x55f98845dd72 <unknown>\\n#16 0x55f9886dbfb6 <unknown>\\n#17 0x55f9886df02d <unknown>\\n#18 0x55f9886deac6 <unknown>\\n#19 0x55f9886df4d5 <unknown>\\n#20 0x55f9886e590b <unknown>\\n#21 0x55f9886df856 <unknown>\\n#22 0x55f9886b8b0d <unknown>\\n#23 0x55f9886f8265 <unknown>\\n#24 0x55f9886f845f <unknown>\\n#25 0x55f98870604f <unknown>\\n#26 0x7f91dba96ea7 start_thread\\n',
>   startTimestamp: 1693726766325,
>   endTimestamp: 1693727085985,
>   version: '3.3.4'
> }
> ```

Can this timeout be increased? @ilike2burnthing

**Comment by whatusername000** [comment]
> > If you run the simple curl command above, does that work?
> 
> `Timed out receiving message from renderer: 300.000` this timeout is 300s, which I think is the cause
> 
> ```
> {
>   status: 'error',
>   message: 'Error: Error solving the challenge. Message: timeout: Timed out receiving message from renderer: 300.000\\n  (Session info: chrome=116.0.5845.140)\\nStacktrace:\\n#0 0x55f98870d023 <unknown>\\n#1 0x55f9884299a8 <unknown>\\n#2 0x55f988412441 <unknown>\\n#3 0x55f988412216 <unknown>\\n#4 0x55f988410cdb <unknown>\\n#5 0x55f9884112fd <unknown>\\n#6 0x55f988425a53 <unknown>\\n#7 0x55f988426a32 <unknown>\\n#8 0x55f988433faf <unknown>\\n#9 0x55f988437f31 <unknown>\\n#10 0x55f9884118c7 <unknown>\\n#11 0x55f988433df0 <unknown>\\n#12 0x55f9884a99bb <unknown>\\n#13 0x55f988491bb3 <unknown>\\n#14 0x55f98845c9de <unknown>\\n#15 0x55f98845dd72 <unknown>\\n#16 0x55f9886dbfb6 <unknown>\\n#17 0x55f9886df02d <unknown>\\n#18 0x55f9886deac6 <unknown>\\n#19 0x55f9886df4d5 <unknown>\\n#20 0x55f9886e590b <unknown>\\n#21 0x55f9886df856 <unknown>\\n#22 0x55f9886b8b0d <unknown>\\n#23 0x55f9886f8265 <unknown>\\n#24 0x55f9886f845f <unknown>\\n#25 0x55f98870604f <unknown>\\n#26 0x7f91dba96ea7 start_thread\\n',
>   startTimestamp: 1693726766325,
>   endTimestamp: 1693727085985,
>   version: '3.3.4'
> }
> ```

Can this timeout be increased? @ilike2burnthing

**Comment by ilike2burnthing** [comment]
You could try setting the ENV `BROWSER_TIMEOUT` - https://github.com/FlareSolverr/FlareSolverr#environment-variables

However, each of your attempts is resolved in a second or two, and if you're getting into double digit attempts then I don't think time is your problem. Enable HTML logging and see what is being returned for those attempts.

**Comment by whatusername000** [comment]
> You could try setting the ENV `BROWSER_TIMEOUT` - https://github.com/FlareSolverr/FlareSolverr#environment-variables
> 
> However, each of your attempts is resolved in a second or two, and if you're getting into double digit attempts then I don't think time is your problem. Enable HTML logging and see what is being returned for those attempts.

cannot reproduce double digit attempts now.about 4 or 5 attmpts,process will enter the waiting period.After setting `BROWSER_TIMEOUT`, the problem was resolved

**Comment by Woody-Stock** [comment]
OK maybe I missed something but the issue isn't solved for me.

2023-09-04 11:16:26 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://extratorrent.st/', 'proxy': {}}
2023-09-04 11:16:27 INFO     Challenge detected. Selector found: #challenge-spinner
2023-09-04 11:17:23 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://extratorrent.st/'}
2023-09-04 11:17:24 INFO     Challenge detected. Selector found: #challenge-spinner
2023-09-04 11:17:27 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-09-04 11:17:27 INFO     Response in 61.131 s
2023-09-04 11:17:27 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error

It's doing this on every request that needs Flaresolverr (both in Prowlarr and Jackett).

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have problems, open a new issue, providing the information requested.
